### ISSUE TITLE
 Add a section to give thanks to all of the Sponsors

### ISSUE THREAD

**Issue by will-ww** [wuhan2020/wuhan2020.github.io#100]
1、Slackbot  8:16 AM
Your workspace is getting a free trial of Slack's Standard Plan through February 29th!:tada: On the Standard plan, your team can now see all your past messages and files, add guests to your workspace, make group calls, and more.

2、Shimo
Free enterprise edition for wuhan2020 team

3、…… 

**So, we need to add a section to give thanks to all of the Sponsors, e.g. shimo, slack, …**

**Comment by thinkinnight** [comment]
@lovepoem 我已经把这个issue移到wuhan2020.github.io这个repo下了

**Comment by iLtc** [comment]
像 [贡献者](https://community.wuhan2020.org.cn/zh-cn/docs/developers/developers_dev.html) 那样单独做成一个 赞助商 的页面吗？

还是放在全局的底部？

**Comment by lovepoem** [comment]
在首页的底部放一个就行了吧
