### ISSUE TITLE
个人创建了一个疫情信息导航网站，且项目已在github开源，有相关信息可以直接拿去用

### ISSUE THREAD

**Issue by wertycn** [wuhan2020/wuhan2020.github.io#101]
github 项目地址 ：https://github.com/wertycn/nCoV
正式环境地址： http://nav.werty.cn/
目前已提供 实时疫情，防疫知识，在线义诊，谣言鉴定，举报通道模块，希望能有所帮助

**Comment by lovepoem** [comment]
hi ， @wertycn 
早期没有看到你的作品，我还了发了一个issue https://github.com/wuhan2020/wuhan2020/issues/324 
[提案] 将Wuhan2020社区网站作为金矿旁边的供水者（在社区官网帮各家“抗疫应用” 做宣传导流）

我邮件你了

**Comment by WeileiZeng** [comment]
武汉开源 OpenSourceWuhan
集齐了开源平台上支援武汉的项目，是一个连结各个开源项目的入口。欢迎互相引用！

站点：
https://weileizeng.github.io/OpenSourceWuhan/

**Comment by lovepoem** [comment]
closed via https://github.com/wuhan2020/wuhan2020/issues/346
