### ISSUE TITLE
添加项目列表频道，介绍推广在社区孵化的项目

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#103]
## 描述功能要求
在社区网站加一个“项目列表”频道，介绍推广社区孵化的产品，
这个页面列出所有社区孵化的项目： 类似https://projects.apache.org/projects.html
我们项目少，可以加上图片详情描述

https://community.wuhan2020.org.cn/zh-cn/projects/index.html
### 如果有的话，请附图
![image](https://user-images.githubusercontent.com/827112/73894925-eae0ba00-48b8-11ea-8cb7-e20f8a577373.png)

**Comment by imononoke** [comment]
hi @lovepoem  I wanna have a try.

**Comment by iLtc** [comment]
@imononoke Thanks for helping. I have assigned this issue to you!

**Comment by WeileiZeng** [comment]
武汉开源OpenSourceWuhan 集结了支援武汉的开源项目，是一个连结各个开源项目的入口。

站点：
https://weileizeng.github.io/OpenSourceWuhan/

欢迎一起讨论或者引用，其实这个也可以算一个wuhan2020的子项目

**Comment by imononoke** [comment]
hi @iLtc @WeileiZeng 请问“项目列表”这个页面有设计过大致布局吗？

**Comment by shawnpanda** [comment]
@imononoke 我跟lovepoem微信上联系了下，已经开始做个基本的，来替代现有的页面，我等下会做个pull request，如果你想更改，欢迎看一下
