### ISSUE TITLE
一个印度用户登录英文首页报错

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#106]
## 当前问题
一个印度用户登录英文首页报错

 
![image](https://user-images.githubusercontent.com/827112/73913165-49298f00-48f1-11ea-81d2-7b61a704760d.png)

## 期待的正确输出

页面正常

**Comment by purple-force** [comment]
这是哪个页面，浏览器崩了吧

**Comment by lovepoem** [comment]
好像不是我们的页面，别的媒体的
