### ISSUE TITLE
[媒体文章搬到社区网站] 文案xx -武汉莫慌

### ISSUE THREAD

**Issue by ch-shumin** [wuhan2020/wuhan2020.github.io#107]
团队加班加点制作超暖心“武汉莫慌”漫画，献给所有为疫情加油的你！

在过去的两周，肆虐的疫情和不断增加的疑似确诊病例下，我们看到的是各种求助和悲伤的信息，看到了很多抗击在肺炎第一线的故事，还有更多的，是普通和平凡的我们，焦虑，担心，害怕，恐慌，和愤怒。

当你感觉到无法从这样的情绪网中挣扎出来时，可以尝试点击一下这个链接，武汉莫慌，我们都在：

https://q.eqxiu.com/s/5aYnTQLR?eqrcode=1&share_level=7&from_user=2020020653677c58&from_id=a0873018-c&share_time=1580966341969&from=groupmessage&isappinstalled=0

**Comment by GindaChen** [comment]
这个应该怎么搬运到社区里……

**Comment by iLtc** [comment]
找原来的团队把原图要过来？我看了一下这个网站里的图片质量不高，应该是压缩过给手机看的

**Comment by GindaChen** [comment]
（哦哦我终于点开了……）这个漫画已经在翻译了
但是我们怎么呈现这个内容还是一个问题

**Comment by iLtc** [comment]
我觉得直接把图片竖着贴在网页上就好啦？

但一定要高清的，不然看起来很累

**Comment by jeremy0519** [comment]
> 找原来的团队把原图要过来？我看了一下这个网站里的图片质量不高，应该是压缩过给手机看的



> 我觉得直接把图片竖着贴在网页上就好啦？
> 
> 但一定要高清的，不然看起来很累

同意
