### ISSUE TITLE
[Question] 如何新增一个语言

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#119]
## 描述你需要修改或新增的文档

我记得我们曾经有一个README描述如何支持一个新的语言。

这个README现在还健在吗？希望能post出来作为文档给新人使用

### 如果有的话，请附图

无

## 额外的信息

无

**Comment by lovepoem** [comment]
在README上有

**Comment by GindaChen** [comment]
> How To Add One New Language
> If you want to add a new language, such as Thai.
> Please append the element: { value: 'th-th', text: 'ภาษาไทย' } to the langlist variable of site config/site.js.
> Then please add directories named th-th in docsand blog directories , here you can add documents in this language .
> notice : Of course, you can also see langlist variables in several other files. This is just a bottom line measure, and you don't have to modify it..

所以我们没有自动化的方法对吧…… 现在要加一个语言的话需要edit 6个json file

**Comment by lovepoem** [comment]
目前确实需要手工修改一些

**Comment by chenrui333** [comment]
是的，其实也不是特别复杂。

**Comment by chenrui333** [comment]
我们可以单开新的 issue 加新的语言。
