### ISSUE TITLE
添加一个全站访问数量统计，总pv & 总uv

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#136]
添加一个全站访问数量统计，总pv & 总uv

**Comment by jeremy0519** [comment]
貌似不蒜子可以统计pv
`<script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>`
`<span id="busuanzi_container_site_pv">本站总访问量<span id="busuanzi_value_site_pv"></span>次</span>`

**Comment by lovepoem** [comment]
> 貌似不蒜子可以统计pv
> `<script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>`
> `<span id="busuanzi_container_site_pv">本站总访问量<span id="busuanzi_value_site_pv"></span>次</span>`

可以尝试下将各个页面加上点击量，页脚加上pv uv

**Comment by iLtc** [comment]
@jeremy0519 你有兴趣做一下这个 issue 吗？

**Comment by jeremy0519** [comment]
我技术方面不太行，代码是我从官网上找的

**Comment by iLtc** [comment]
Okay, 我稍后做一下

**Comment by iLtc** [comment]
@lovepoem 不蒜子可以提供三种数据：本文阅读量 `page_pv`、本站访问量 `site_pv`和本站访客人数 `site_uv`。你觉得要哪几个？

**Comment by lovepoem** [comment]
都要
