### ISSUE TITLE
[doc] README for Translator 

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#141]
Let's pin an issue page referring to the following tutorials to the `translator-guide` at root:
- [ ] Translator 3 min quick start
- [ ] How to add a new language?
- [ ] How to post a task?
- [ ] How to ask for a task, accept a task, and finish a task?

Logistics:
- [ ] Also link these questions in FAQ

**Comment by lovepoem** [comment]
这个就算了吧先
