### ISSUE TITLE
[Italian Update] 门户网意大利语版优化-『主页HOME』

### ISSUE THREAD

**Issue by Atena1118** [wuhan2020/wuhan2020.github.io#149]
- [HOME](https://community.wuhan2020.org.cn/it-it/index.html)
- [DOCUMENTAZIONE](https://community.wuhan2020.org.cn/it-it/docs/overview/what-is-wuhan2020.html)
- [SOSTENITORI](https://community.wuhan2020.org.cn/it-it/docs/developers/developers_dev.html)
- [BLOG](https://community.wuhan2020.org.cn/it-it/blog/index.html)
- [COMMUNITY](https://community.wuhan2020.org.cn/it-it/community/index.html)
- [RISULTATI](https://community.wuhan2020.org.cn/it-it/blog/download.html)
- [PIATTAFORMA INFORMATIVA 2019-NCOV](https://wuhan2020.kaiyuanshe.cn/)

## Cosa fa la community Wuhan2020?

Ciò che stiamo facendo è creare un servizio informazioni, aggiornato in tempo reale, relativo ad ospedali e supporto medico, attività produttive, servizi di approvvigionamento e molto altro. Allo stesso tempo, stiamo reclutando tutti coloro che desiderano dare un contributo alla campagna contro il coronavirus, in modo che tutte le persone che possiedono le adeguate competenze possano contribuire al lavoro di sviluppo nell'ambito delle tematiche ad esse pertinenti e quindi, in accordo con la cultura della comunità Open Source, al raggiungimento del successo attraverso un approccio di cooperazione autogestita.

[Iniziare](https://community.wuhan2020.org.cn/it-it/docs/overview/what-is-wuhan2020.html)[GitHub](https://github.com/wuhan2020/wuhan2020)

[![img](https://img.alicdn.com/tfs/TB1FlB1JwHqK1RjSZFPXXcwapXa-32-32.png)Star5156](https://github.com/wuhan2020/wuhan2020)[![img](https://img.alicdn.com/tfs/TB1zbxSJwDqK1RjSZSyXXaxEVXa-32-32.png)Fork759](https://github.com/wuhan2020/wuhan2020/fork)

![img](https://community.wuhan2020.org.cn/images/wuhan2020-header-image.png)

### Presentazione della community

- 

  #### Piattaforma informativa per la prevenzione epidemica del nuovo coronavirus

  Sviluppo comunitario di un sistema informativo. Facilitare lo scambio di informazioni tra fornitori di risorse (donatori di risorse mediche e fornitori di supporto medico gratuito, società di servizi logistici, strutture alberghiere e di ristorazione, ecc.) e coloro che hanno bisogno di aiuto (ospedali ed altre strutture sanitarie, persone localizzate nelle zone colpite, ecc), in modo da facilitare ed accelerare il sostegno della popolazione nelle zone colpite.

- 

  #### Community Wuhan2020

  Ad oggi la community Wuhan2020 ha accolto più di 3000 volontari provenienti da diversi paesi. Ne fanno parte programmatori, product manager, progettisti, project manager, analisti dati, raccoglitori di informazioni, traduttori, operatori di comunicazione, studenti, ecc. Attraverso l'istituzione di un sistema informativo, l'analisi e la predizione dati, la community contribuisce alla lotta contro il nuovo coronavirus.

![img](https://community.wuhan2020.org.cn/images/wuhan2020-logo-gray.png)

website powered by docsite

### Il Nostro Motto

Tutti insieme uniti, ce la faremo ! 

- Documentazione

  [Di cosa si occupa Wuhan2020?](https://community.wuhan2020.org.cn/it-it/docs/overview/what-is-wuhan2020.html)

  [Inizia subito](https://community.wuhan2020.org.cn/it-it/docs/dev/quickstart.html)

  [Segnala un problema riguardo il documento](https://github.com/wuhan2020/wuhan2020.github.io/issues/new)

  [Modifica questa pagina su GitHub](https://github.com/wuhan2020/wuhan2020.github.io)

- Risorse

  [Blog](https://community.wuhan2020.org.cn/it-it/blog/index.html)

  [Community](https://community.wuhan2020.org.cn/it-it/community/index.html)

Copyright © 2020 Wuahan2020

————————————

 @GindaChen @chenrui333  
我不知道这样呈现对不对。。。如果不对， 你们及时沟通我，我再重新提个issue。
另外我需要说下，无论是 Typora 还是在这里，像王欣 @lovepoem   老师说的那样【对变更的地方加颜色】好像不可以操作诶。。。

**Comment by GindaChen** [comment]
我感觉好像不太对 像 Star Fork 这样的metadata不应该显示在issue page上

@Atena1118 正确的做法是对这里进行文本改动：
https://github.com/wuhan2020/wuhan2020.github.io/blob/b5672af04ed3d0b3eab6f978999426bc67d74ec0/site_config/home.js#L40-L76

@lovepoem @TechQuery 
但是按照我们今天的说法 @Atena1118 做的确实没有问题。如果有建议的话希望提出。

**Comment by Atena1118** [comment]
> 我感觉好像不太对 像 Star Fork 这样的metadata不应该显示在issue page上
> 
> @Atena1118 正确的做法是对这里进行文本改动：
> https://github.com/wuhan2020/wuhan2020.github.io/blob/b5672af04ed3d0b3eab6f978999426bc67d74ec0/site_config/home.js#L40-L76
> 
> @lovepoem @TechQuery
> 但是按照我们今天的说法 @Atena1118 做的确实没有问题。如果有建议的话希望提出。

但是，让翻译人员 面对 这种 js 代码，可能不太友好噢。。。。哈哈哈

**Comment by GindaChen** [comment]
对所以我才想看看 @lovepoem @TechQuery 有什么看法

我感觉最好的还是在 3 min tutorial （我还没提交估计今天我也写不完……）里面把`doc` 和页面`component`文本的区别写清楚。改动docsite或者js都确实比较麻烦

**Comment by iLtc** [comment]
要不咱们建个表格，把要翻译的部分摘出来放进表格里，然后每种语言在后面分列排好，再用颜色标注未翻译、已翻译、已发布几种状态

**Comment by GindaChen** [comment]
> 要不咱们建个表格，把要翻译的部分摘出来放进表格里，然后每种语言在后面分列排好，再用颜色标注未翻译、已翻译、已发布几种状态

哎 我也感觉这样比较好管理……但我感觉还是要让翻译者区分什么是doc什么是站点信息 不然的话还是会比较混乱

**Comment by GindaChen** [comment]
@Atena1118 
我不太理解 DOCUMENTAZIONE 为啥不能是 DOCS ?

**Comment by iLtc** [comment]
@GindaChen 翻译组目前有个类似的表格。他们希望现在能把已经翻译好的东西先发布出来，所以接下来我会协助他们尽快发布

**Comment by GindaChen** [comment]
> @GindaChen 翻译组目前有个类似的表格。他们希望现在能把已经翻译好的东西先发布出来，所以接下来我会协助他们尽快发布

你发布一个issue吧 我也准备把所有的doc 搬过来
你是说石墨表格吗？

**Comment by iLtc** [comment]
> 你是说石墨表格吗？

这个表格，我不知道你能不能打开 https://shimo.im/sheets/PhD3yRJKCJr8HcpP/

**Comment by GindaChen** [comment]
> > 你是说石墨表格吗？
> 
> 这个表格，我不知道你能不能打开 https://shimo.im/sheets/PhD3yRJKCJr8HcpP/

对我就这个意思 你如果打算搬运的话可以开一个epic issue把所有需要搬运的放上来吗？这样如果你需要分工我也可以和你协调

**Comment by iLtc** [comment]
我等翻译组醒了之后问问还有哪些要发布，然后开 issues

**Comment by GindaChen** [comment]
> 我等翻译组醒了之后问问还有哪些要发布，然后开 issues

我建议先开issue 然后搬能搬的 到时候等他们醒来我们再协调就好

**Comment by GindaChen** [comment]
如果你搬的话 我就先把语言相关的issue解决一下
