### ISSUE TITLE
更新官方贡献者名单

### ISSUE THREAD

**Issue by chenrui333** [wuhan2020/wuhan2020.github.io#152]
## 描述你需要修改或新增的文档

https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/docs/zh-cn/developers/developers_dev.md

### 如果有的话，请附图

![image](https://user-images.githubusercontent.com/1580956/74092002-8413fa00-4a8c-11ea-8127-ab2936a40822.png)

**Comment by lovepoem** [comment]
Closed  via  https://github.com/wuhan2020/wuhan2020.github.io/pull/201
