### ISSUE TITLE
[Doc] Document Transfer Epic Issue

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#154]
This epic issue defines what documents needs to be transferred from the [shimo](https://shimo.im/sheets/PhD3yRJKCJr8HcpP/MODOC) to this repo. 

If you would like to help transferring document, first comment below and let us know which one(s) you're going to transfer. Then raise an issue indicating the transferring of documents.

**Comment by lovepoem** [comment]
暂时关闭，如果需要请随时打开
