### ISSUE TITLE
[Product] Unify name to Wuhan2020

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#155]
We have to agree on one product name. My suggestion is **Wuhan2020** because that is
1. The common usage in English
2. The most direct way to convey our idea
3. Better than `WUHAN2020` and `wuhan2020`: all capital `WUHAN` and all lower case `wuhan` shall never be used
4. Better than `Wuhan 2020`: we don't need a space when `Wuhan2020` is a movement that will be hashtaged, advertised, and propagaated. E.g.: #MeToo, #GenderEquality, etc

**Comment by GindaChen** [comment]
This is a minor issue. See if our product team has any suggestion on this.

**Comment by chenrui333** [comment]
From purely engineering perspective, wuhan2020 is desired.

From product perspective, Wuhan2020 may be more syntax meaningful.

**Comment by WeileiZeng** [comment]
what us the trouble with those different versions?

**Comment by jeremy0519** [comment]
Is there anyone still working on this issue?

**Comment by lovepoem** [comment]
> Is there anyone still working on this issue?

No

**Comment by zhaofeng-shu33** [comment]
it can be closed, I think
