### ISSUE TITLE
DeepScan issue reports

### ISSUE THREAD

**Issue by chenrui333** [wuhan2020/wuhan2020.github.io#162]
dashboard for the issue report, 
https://deepscan.io/dashboard/#view=project&tid=7382&pid=9495&bid=123841

![image](https://user-images.githubusercontent.com/1580956/74093832-ab2af580-4aa5-11ea-82ee-12b0e1f2b57c.png)

**Comment by jeremy0519** [comment]
The link above redirects to deepscan homepage.
