### ISSUE TITLE
[Doc] Need French Translation for meta data and index page

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#179]
If you look at the French page, you will notice that many text are still in English -- `home`, `docs`, etc.
This is because they sit in the `site_config/*.js`, and need to directly edit the `js` to add the language there. Since it is very inconvienient to most translators, we didn't release this issue for a long time.

If you would like to address this issue:
1. Join our [shimo](https://shimo.im/sheets/PhD3yRJKCJr8HcpP/QtAt0) sheet 
2. Go to the `French` column
3. Translate the text from a language to French, then mark that cell **yellow**
4. Comment below about the changes. We will uplaod them by hand (or if you know exactly how the text is mapped to a file in `site_config`, you can raise a PR about the changes).

**Comment by GindaChen** [comment]
@AnnaCICI Would love you to take a look if you have time :D

**Comment by AnnaCICI** [comment]
> @AnnaCICI Would love you to take a look if you have time :D

No problem 👌

**Comment by iLtc** [comment]
@AnnaCICI Do you have access to the [Shimo document](https://shimo.im/sheets/PhD3yRJKCJr8HcpP/QtAt0)?

**Comment by AnnaCICI** [comment]
> @AnnaCICI Do you have access to the [Shimo document](https://shimo.im/sheets/PhD3yRJKCJr8HcpP/QtAt0)?

I can modify directly in site_config/*.js. 
/self-assign does not work in repo wuhan2020.github.io ?

**Comment by GindaChen** [comment]
> > @AnnaCICI Do you have access to the [Shimo document](https://shimo.im/sheets/PhD3yRJKCJr8HcpP/QtAt0)?
> 
> I can modify directly in site_config/*.js.

Since we maintained a csv for the doc, would you like to edit the Shimo then commit the changes here in `site_config`? 

If you already edit the text in `site_config`, then you can raise a PR and then we may copy those changes later. Just want to make sure the two platforms are synced.


> /self-assign does not work in repo wuhan2020.github.io ?

I see - I will see what hapened.

**Comment by lovepoem** [comment]
Close via https://github.com/wuhan2020/wuhan2020.github.io/pull/199
