### ISSUE TITLE
从石墨表格生成site_config各文件

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#180]
Relates to #181 

在[石墨表格](https://shimo.im/sheets/PhD3yRJKCJr8HcpP/QtAt0)中，我们将`site_config`中需要各翻译者翻译的文本都粘贴了上去。当翻译者翻译完成后，技术人员将翻译文本粘贴到`site_config`对应位置并提交。这种更改的方式比较麻烦。

建议：
1. 写一个简单的脚本将表格（csv）反向构造json
2. 将json object转换到`js`中并导出
(如果#181可以实现则生成yml)

（待讨论）

**Comment by chenrui333** [comment]
那个石墨文档我好像看不了。

**Comment by chenrui333** [comment]
我们现在有多少语言要做？

**Comment by GindaChen** [comment]
当前支持的没有很多：中英日意法
可能不会支持其他语言

**Comment by iLtc** [comment]
@GindaChen 我打算加个 Google Translate 的按钮，这样就不用增加其他语言了

**Comment by GindaChen** [comment]
@iLtc 
1. 加一个Translate 按钮。如果确实没有这个language的话就translate。
2. 配置docsite让它默认显示英文文档（而不是直接跳转到英文）。注意这个有区别：我们当前是直接跳转到英文文档，但是这样的话用户要回到原来的语言就要通过右上角的下拉菜单转换语言。（中文应该不会出现这个问题因为所有文档中文都有）

@Atena1118 估计会反对全文本用Google Translate。我也觉得至少要让用户看到一个比较忠实的文本，所以在当前语言显示默认语言的doc是一个比较好的做法

**Comment by GindaChen** [comment]
你先提这个PR吧 毕竟这个功能确实很有用

**Comment by chenrui333** [comment]
> @GindaChen 我打算加个 Google Translate 的按钮，这样就不用增加其他语言了

这个还挺有意思的。

**Comment by lovepoem** [comment]
通过在i18n的配置，暂时解决让各个语言分开的问题。先关闭这个问题
