### ISSUE TITLE
[low priority] Bug in English page

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#20]
![image](https://user-images.githubusercontent.com/32371474/73602232-0ef96f80-4536-11ea-9274-859dbe0b1bd6.png)

Duplicates tabs occur.

**Comment by chenrui333** [comment]
It got fixed in #27, closing the issue now.

![image](https://user-images.githubusercontent.com/1580956/73604863-3d427380-4565-11ea-96b8-3e07023b005d.png)
