### ISSUE TITLE
QRCode of our wechat group in this page is now unavailable.

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#205]
@GindaChen 
1 more thing.
plz note that the QRCode of our wechat group in this page is now unavailable.

_Originally posted by @Pandar1Young in https://github.com/wuhan2020/wuhan2020.github.io/pull/172#issuecomment-584506765_

**Comment by jeremy0519** [comment]
这个二维码就是信息组微信群的二维码
[二维码地址](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/images/docs/QRCode.jpeg)

**Comment by jeremy0519** [comment]
要更新二维码，2月7日就过期了

**Comment by jeremy0519** [comment]
有人有信息组的微信群二维码吗？

**Comment by lovepoem** [comment]
微信导流二维码本身是7天过期的，后面都进入slack
