### ISSUE TITLE
pt-br language is in loop

### ISSUE THREAD

**Issue by kevenleone** [wuhan2020/wuhan2020.github.io#208]
Hello, i've created this PR #204, to add a new language (pt-br) on docs and website. 

And everything worked fine in my environment, i've executed the build and ran with python as mentioned on docs, no problem ocurred.

But here: https://community.wuhan2020.org.cn/pt-br

The website is reloading in loop, probably this redirect.ejs is doing that, but i don't know why this is happening.

**Comment by lovepoem** [comment]
I have fixed via https://github.com/wuhan2020/wuhan2020.github.io/commit/7e5b7bd8b07664f4bd75b120279aaec6d1553757

**Comment by kevenleone** [comment]
great @lovepoem, thanks
