### ISSUE TITLE
Server 404!

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#218]
## 当前问题
[https://wh.opensource-service.cn/](https://wh.opensource-service.cn/) is 404. What happened?

![image](https://user-images.githubusercontent.com/32371474/74393298-5356fc00-4dcf-11ea-8ee2-d90dcdb8991a.png)

**Comment by lovepoem** [comment]
我用chrome 看起来是好的

**Comment by GindaChen** [comment]
哦哦我用chrome在clear cache就好了
