### ISSUE TITLE
需要在社区页将所有的Slack chanel 列出来

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#22]
需要在https://wuhan2020.github.io/zh-cn/community/index.html 页面将所有的Slack chanel 列出来

_Originally posted by @lovepoem in https://github.com/wuhan2020/wuhan2020.github.io/issues/8#issuecomment-581097655_

**Comment by lovepoem** [comment]
需要将  https://wuhan2020.github.io/zh-cn/blog/wuhan2020-official-announcement.html、
列出的Slack Channel 都列在https://wuhan2020.github.io/zh-cn/community/index.html

**Comment by damingerdai** [comment]
提供设计稿吗？

**Comment by GindaChen** [comment]
如果暂时没有涉及的话 直接参考https://wuhan2020.github.io/zh-cn/docs/dev/quickstart.html 里面的Slack表格然后看看docsite render成什么样吧？

**Comment by damingerdai** [comment]
如果[quickstart](https://wuhan2020.github.io/zh-cn/docs/dev/quickstart.html)页面已经有了列表，为什么不直接跳转过去呢？

**Comment by GindaChen** [comment]
好问题 @lovepoem 你怎么看？我觉得初衷是希望放在首页方便链接/查看，不过直接跳转也可行。
如果 @damingerdai  觉得阅读的顺序不大会受太大影响的话跳转也OK

**Comment by lovepoem** [comment]
我的意思是社区页应该作为，沟通方式展示的第一列表，不用再跳转了。因为现在channel list也存在好几个地方，而且都不全
