### ISSUE TITLE
【请教】docsite 安装完查看版本报错, docsite start报错相同

### ISSUE THREAD

**Issue by keeStep** [wuhan2020/wuhan2020.github.io#224]
【报错在最下面】
docsite@1.3.9-wuhan2020.5 postinstall D:\nvm\v8.16.0\node_modules\docsite

opencollective-postinstall

Thank you for using docsite!
If you rely on this package, please consider supporting our open collective:

https://opencollective.com/docsite/donate

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN co-mocha@1.2.2 requires a peer of mocha@>=1.18 <6 but none is installed. You must install peer dependencies yourself.
npm WARN acorn-jsx@5.1.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN docsite@1.3.9-wuhan2020.5 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 684 packages from 765 contributors and audited 17589 packages in 123.383s
found 7 vulnerabilities (1 moderate, 5 high, 1 critical)
run npm audit fix to fix them, or npm audit for details

D:\nvm\v8.16.0\node_modules\docsite>docsite -V
D:\nvm\v8.16.0\node_modules\docsite\lib\generateJSONFile.js:26
langList = [{
^

**TypeError: Cannot destructure property langList of 'undefined' or 'null'.
at Object. (D:\nvm\v8.16.0\node_modules\docsite\lib/generateJSONFile.js:26:5)
at Module._compile (module.js:653:30)
at Module._compile (D:\nvm\v8.16.0\node_modules\docsite\node_modules\pirates\lib\index.js:99:24)
at Module._extensions..js (module.js:664:10)
at Object.newLoader [as .js] (D:\nvm\v8.16.0\node_modules\docsite\node_modules\pirates\lib\index.js:104:7)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)`**

**Comment by iLtc** [comment]
我下了最新版的源码，安装包之后没有报错，启动的时候也没有报错。

请问你有修改过源码吗？我注意到你的错误中出现了 `langList = [{`，这个应该是我们的代码。

**Comment by purple-force** [comment]
这个是docsite的问题，我修复下

**Comment by purple-force** [comment]
已发布，`npm uninstall docsite -g && npm i docsite@wuhan2020 -g`

**Comment by iLtc** [comment]
我刚刚碰到了跟你一样的错误。

看了一下虽然 `docsite` 源代码有问题，但跟我们的操作也有关系。

因为 `docsite start` 要在项目根目录下执行，如果在子目录下执行，由于找不到一些配置文件，会触发 `docsite` 创建新站点的流程，并进一步触发源代码的错误。

但是在项目根目录执行 `docsite start` 就不会有问题，因为所有文件是齐全的。

**Comment by keeStep** [comment]
嗯我昨晚也解决了，由于npm概念比较陌生，以为install完看到的docsite目录就是项目目录，就去start了，后来重新建了新文件夹作为项目目录然后初始化了一下就可以了。初始化和把项目克隆下来是一样的


| |
Kee
|
|
邮箱：13651486829@163.com
|

Signature is customized by Netease Mail Master

On 02/16/2020 07:31, Alan Luo wrote:

我刚刚碰到了跟你一样的错误。

看了一下虽然 docsite 源代码有问题，但跟我们的操作也有关系。

因为 docsite start 要在项目根目录下执行，如果在子目录下执行，由于找不到一些配置文件，会触发 docsite 创建新站点的流程，并进一步触发源代码的错误。

但是在项目根目录执行 docsite start 就不会有问题，因为所有文件是齐全的。
