### ISSUE TITLE
[媒体文章搬到社区网站] 开源共抗：疫情信息导航站点正式入驻wuhan2020开源社区

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#227]
https://mp.weixin.qq.com/s/Cb7tPVjBe1aVcGiavXs_mg

标题作者请写媒体和作者名字
请使用 [Typora](https://www.typora.io/)  将`html`页面转化为`markdown`,放到社区频道.图片尽量下载到本站

**Comment by jeremy0519** [comment]
Typora怎么把html页面转换为markdown，为什么导入选项没有html？

**Comment by lovepoem** [comment]
> Typora怎么把html页面转换为markdown，为什么导入选项没有html？

直接在页面粘贴过来

**Comment by jeremy0519** [comment]
Someone can move it to done in project page.
