### ISSUE TITLE
增加社区Hackathon活动页面

### ISSUE THREAD

**Issue by mb0ma** [wuhan2020/wuhan2020.github.io#238]
## 额外的信息
1. 2月17日前完成Landing Page, phase 1, 信息发布功能
Action: 明确页面主要内容模块 - 吴雪
Action: 提交需求文档 - Tianyi
Action: 设计 - Kate
Action: 将Landing Page的设计同步到海外流量入口RunTheWorld - Xiaoyin (RunTheWorld)

2. 2月17日前完成比赛内容和参赛规则 - Action: 王老师、Frank

3. 需在报名开始日之前完成Landing Page, phase 2， 注册

**Comment by iLtc** [comment]
@lovepoem 占位符页面要不要先建起来？内容后面再添加

**Comment by lovepoem** [comment]
@sunshinemingo  is trying, you can give her some help  @iLtc

**Comment by iLtc** [comment]
Okay, @sunshinemingo please let me know if you need any help!

**Comment by lovepoem** [comment]
初版 已经在 https://github.com/wuhan2020/wuhan2020.github.io/pull/273 提交

**Comment by lovepoem** [comment]
添加了优化需求  https://github.com/wuhan2020/wuhan2020.github.io/issues/315

关闭这个
