### ISSUE TITLE
image-action does not support webp image

### ISSUE THREAD

**Issue by chenrui333** [wuhan2020/wuhan2020.github.io#243]
From https://github.com/wuhan2020/wuhan2020.github.io/pull/232#issuecomment-586549801
![image](https://user-images.githubusercontent.com/1580956/74596111-c0a99d80-5018-11ea-8a30-21d44667075b.png)

relates to https://github.com/calibreapp/image-actions/issues/31

**Comment by jeremy0519** [comment]
How about changing webp format to jpg?

**Comment by jeremy0519** [comment]
It's not a big problem.
