### ISSUE TITLE
首页的谷歌翻译器对重要内容进行了错误翻译

### ISSUE THREAD

**Issue by keeStep** [wuhan2020/wuhan2020.github.io#254]
## 当前问题
1.中文版：
![image](https://user-images.githubusercontent.com/38199712/74599425-96112080-50bc-11ea-870b-3caa35061da1.png)

2.右上角切换英文版：
![image](https://user-images.githubusercontent.com/38199712/74599431-aa551d80-50bc-11ea-8b5c-de7690eae04f.png)

3.等待谷歌翻译器加载完成后：
![image](https://user-images.githubusercontent.com/38199712/74599451-f30cd680-50bc-11ea-9b46-73d38b86cf14.png)

4.将谷歌翻译器的语言切换为中文（注意，不切换右上角语言）
![image](https://user-images.githubusercontent.com/38199712/74599461-29e2ec80-50bd-11ea-97b7-36844a010bf4.png)

## 期待的正确输出
中文正确应为图1，英文正确应为图2. 

由于本人只认识中英，谷歌翻译器在这两个语言的‘’新型冠状病毒”的翻译都是错误的，本网站的核心目标所在。

请诸位考量下谷歌翻译器的必要性。

**Comment by iLtc** [comment]
你好👋

图3的问题描述不是很清楚，没有办法复现。谷歌翻译器加载后（但用户没有点击需要翻译的语言时）页面内容不应发生变化。

图4的问题确实存在，其根本原因是谷歌翻译器没有收录 nCov 这个短语。不过也可以看到下面描述的小字翻译基本正确。

我在加入这个功能后大概做了测试，大部分词语（比如 新型冠状病毒防疫信息平台）的翻译都比较准确，或者至少可以被理解。个人认为不应该因为 nCov 这个短语翻译错误而否定谷歌翻译的价值。

机器翻译达不到人工翻译的准确性是一直存在的。我们接入机器翻译的目的不是为了取代翻译组同事的人工翻译，而是为翻译组尚未覆盖语言区域，又希望了解 新型冠状病毒防疫状况 的用户以便利。即使我们不提供这个功能，其他语言区域的用户也会通过各种方式（多半还是谷歌翻译）来查看翻译过的页面结果。

**Comment by keeStep** [comment]
> 你好👋
> 
> 图3的问题描述不是很清楚，没有办法复现。谷歌翻译器加载后（但用户没有点击需要翻译的语言时）页面内容不应发生变化。
> 
> 图4的问题确实存在，其根本原因是谷歌翻译器没有收录 nCov 这个短语。不过也可以看到下面描述的小字翻译基本正确。
> 
> 我在加入这个功能后大概做了测试，大部分词语（比如 新型冠状病毒防疫信息平台）的翻译都比较准确，或者至少可以被理解。个人认为不应该因为 nCov 这个短语翻译错误而否定谷歌翻译的价值。
> 
> 机器翻译达不到人工翻译的准确性是一直存在的。我们接入机器翻译的目的不是为了取代翻译组同事的人工翻译，而是为翻译组尚未覆盖语言区域，又希望了解 新型冠状病毒防疫状况 的用户以便利。即使我们不提供这个功能，其他语言区域的用户也会通过各种方式（多半还是谷歌翻译）来查看翻译过的页面结果。

你好，明白大家对谷歌翻译的依赖以及信任和推崇，可能是目前没有录入他的库。
图三的英语其实会出现好几种形式：
1.打开https://community.wuhan2020.org.cn，默认是英文版，然后点击谷歌翻译选择英文，他会重新翻译：
![image](https://user-images.githubusercontent.com/38199712/74602071-fd8c9780-50df-11ea-921e-2432b10cd630.png)

2.把 1 打开的页面关掉 重新打开 1 的链接，此时页面是人工翻译的英文，同时谷歌翻译会自动加载英文翻译，等待一会【国内比较慢】就回出现图1的字样。

3.在2的基础左上角切换为中文，由于谷歌翻译器插件目前是英文，随后会将中文页面谷歌翻译为英文，这时是由中文进行的翻译：
![image](https://user-images.githubusercontent.com/38199712/74602132-aa671480-50e0-11ea-9d85-efd91b03928f.png)

4.同理保持浏览器谷歌翻译插件为英文不变，右上角再切换为其他语言，由于各语言之间对同一短语的描述在谷歌不一致，就会导致谷歌翻译器将人工的各语种（包含英语）翻译成英语时，结果是有差异的。

当然，我也同意你的说法，谷歌翻译是世界各国的神器。

**Comment by WeileiZeng** [comment]
已经提供了英文版，别人应该不会用谷歌翻译了吧

**Comment by lovepoem** [comment]
暂时关闭
