### ISSUE TITLE
Wrong titles/links in the italian version of the documentation section’s side menu

### ISSUE THREAD

**Issue by sciulli** [wuhan2020/wuhan2020.github.io#263]
Some parts of the italian version of the documentation section’s side menu contain wrong titles and links, please correct as follows:

- Panoramica
-- Di cosa si occupa Wuahan2020?
-- FAQ
- Guide per gli utenti
-- Guida alla piattaforma di prevenzione epidemica COVID-19
- Guide per gli sviluppatori
-- Quickstart
-- Flusso di lavoro del team (Cinese)
-- Guida alla raccolta dati
-- Guida all’iscrizione alla mailing list (Cinese)
-- Diagramma dell'architettura (Inglese)
-- Guida alla partecipazione (Inglese)
-- Gestione del repository su GitHub (Inglese)

**Information guide wrong link and title:**
`<a href="/en-us/docs/dev/information-guide.html" target="_self">Guida alla raccolta dei dati (Inglese)</a>`
**should be:**
`<a href="/it-it/docs/dev/information-guide.html" target="_self">Guida alla raccolta dati</a>`

@GindaChen, these bugs are those I briefly informed you about, please have a look.

Thanks!

**Comment by GindaChen** [comment]
Thanks! Anyone who knows about the current design of `site_config` is welcomed to take this issue
I can also take this issue later too.

**Comment by jeremy0519** [comment]
能说的更详细一点吗？

**Comment by lovepoem** [comment]
> 能说的更详细一点吗？

说是意大利语的左侧菜单，链接不对，链到英文版了。

**Comment by lovepoem** [comment]
现在需要检查i18n的意大利版本的链接

**Comment by jeremy0519** [comment]
有些文章是因为没有翻译成意大利文
