### ISSUE TITLE
bug: 信息收集指南 里的微信 QR code 图片无法显示

### ISSUE THREAD

**Issue by tenCats** [wuhan2020/wuhan2020.github.io#28]
![image](https://user-images.githubusercontent.com/6828552/73604195-917e3f80-45c7-11ea-908c-2e91e87ab635.png)

**Comment by chenrui333** [comment]
我来看看

**Comment by tenCats** [comment]
@chenrui333  Iol I'm fixing this!

**Comment by tenCats** [comment]
这个repo似乎没有bot
