### ISSUE TITLE
同步社区页面到 Gitee 上

### ISSUE THREAD

**Issue by iLtc** [wuhan2020/wuhan2020.github.io#280]
终于决定将社区页面到托管平台从 GitHub Pages 迁移到 Gitee Pages 啦。

以下是计划的步骤：

- [x] 实现 GitHub 代码自动同步到 Gitee，打算通过 Travis CI 执行脚本来实现
- [x] 验证 Gitee 社区页面有没有异常
- [x] 切换域名解析到 Gitee
- [ ] 检测百度收录情况

注意只是将 GitHub Pages 同步到 Gitee Pages，提交代码仍在 GitHub 上进行。

**Comment by iLtc** [comment]
gitee 自动同步已实现，先放任它跑两天看看有没有问题

**Comment by jeremy0519** [comment]
我自己搭的gitee pages百度收录没问题

**Comment by jeremy0519** [comment]
社区页面也没问题

**Comment by WeileiZeng** [comment]
有Gitee链接吗

**Comment by iLtc** [comment]
https://wuhan2020.gitee.io/

**Comment by zhaofeng-shu33** [comment]
why gitee?

**Comment by iLtc** [comment]
@zhaofeng-shu33 

For some reason, GitHub Pages do not work with Baidu Spider, so our site does not show up in Baidu search results.

Also, images on our site load slow for people in China.

**Comment by zhaofeng-shu33** [comment]
It is reported that gitee page does not support custom domains if they haven't registered themselves in ICP system.  So currently we have to use gitee original domain name [wuhan2020.gitee.io](https://wuhan2020.gitee.io) to visit the website.

**Comment by iLtc** [comment]
> It is reported that gitee page does not support custom domains if they haven't registered themselves in ICP system. So currently we have to use gitee original domain name wuhan2020.gitee.io to visit the website.

Yes, you are correct. I think @frank-zsy is working on registering our domain, but due to the epidemic, the process is slow now.

**Comment by jeremy0519** [comment]
好像gitee如果自定义域名的话，必须要gitee pages pro
gitee官网上说的：
> Gitee Pages Pro 是支持自定义域名版本的 Gitee Pages。目前在码云GVP、码云推荐项目和码云付费企业版中可以免费使用。

**Comment by jeremy0519** [comment]
现在这个issue还有人正在做吗？

**Comment by lovepoem** [comment]
> 现在这个issue还有人正在做吗？

还没有结束，别关

**Comment by iLtc** [comment]
还在等备案吧？

**Comment by lovepoem** [comment]
> 还在等备案吧？

嗯

**Comment by zhaofeng-shu33** [comment]
In China, I am afraid `org.cn` is difficult to pass the audit for a community without certificate.

**Comment by lovepoem** [comment]
百度收录还是不行，sitemap抓取会报超时

**Comment by zhaofeng-shu33** [comment]
Why timeout?

**Comment by lovepoem** [comment]
> Why timeout?

不知道 按理说百度抓取的时候应该读取gitee的sitemap,现在速度够快了

**Comment by zhaofeng-shu33** [comment]
Visit the overseas website maybe?

**Comment by lovepoem** [comment]
百度收录不行，暂时关闭

**Comment by zhaofeng-shu33** [comment]
I wonder how to push to gitee without prompt of username and password. @iLtc

**Comment by iLtc** [comment]
> I wonder how to push to gitee without prompt of username and password. @iLtc

There is a sync button on Gitee that we can manually click to triage the sync, but there is no API to do that automatically.

To push the updates automatically, we need either username and password or SSH key. As far as I knew, these are the only two ways to push automatically.

The reason why I choose to not use SSH key is that there is a prompt to accept the server key, and developers are discouraged to override the prompt automatically.

**Comment by zhaofeng-shu33** [comment]
So in this repo, we use "username and password" method?
