### ISSUE TITLE
Add Cache to CI and Deploy

### ISSUE THREAD

**Issue by iLtc** [wuhan2020/wuhan2020.github.io#287]
咱们的 [CI](https://github.com/wuhan2020/wuhan2020.github.io/blob/master/.github/workflows/CI.yml) 和 [Deploy](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/.github/workflows/deploy.yml) 脚本运行时间通常超过 1.5 分钟，而 Travis CI 上的脚本运行时间只要 0.5 分钟。多出来的时间主要浪费在了重复安装依赖上。可以给这两个脚本增加缓存来缩短安装依赖的时间。

可以参考 [GitHub Action Cache](https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows) 的帮助文档。

**Comment by lovepoem** [comment]
Closed via https://github.com/wuhan2020/wuhan2020.github.io/pull/288
