### ISSUE TITLE
志愿者证书[frontend]

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#298]
## 描述功能要求
添加志愿者证书姓名修改页面，作为交互的入口： 
https://community.wuhan2020.org.cn/volunteer/update-name.html

### 如果有的话，请附图
![image](https://user-images.githubusercontent.com/827112/75143258-ad40b580-572f-11ea-8780-152071bedc50.png)

**Comment by lovepoem** [comment]
@Muxxs @DoubleNou

**Comment by lovepoem** [comment]
@Jesson-xmb

**Comment by jesson-xmb** [comment]
1
