### ISSUE TITLE
将Hackathon活动加入项目列表

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#312]
## 描述功能要求
将Hackathon活动加入项目列表

https://community.wuhan2020.org.cn/zh-cn/project/index.html

**Comment by zhaofeng-shu33** [comment]
Need the exact title, github repo url and a passage of description

**Comment by lovepoem** [comment]
项目名称：黑客松
项目描述：黑客松活动是社区举办的创意设计大赛。为了呼吁更多人参与、创造包括产品原型，编码，用户体验设计以及业务/社会影响模型等形式的作品，以对抗新冠病毒疫情。此外，鼓励社会创新，以开源协作来帮助对抗疫情，并在志愿者，机构，企业和平台之间创造共享价值。
线上平台：https://community.wuhan2020.org.cn/zh-cn/hackathon/index.html
github地址：https://github.com/wuhan2020/Hackathon

**Comment by lovepoem** [comment]
![image](https://user-images.githubusercontent.com/827112/75617616-725dd800-5b9c-11ea-9d8b-774b24a1bc19.png)

请在
https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/i18n/zh-cn.js  加上新项目
