### ISSUE TITLE
黑客松社区导流页面优化

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#315]
@Namaste  讲的目前的情况：
1. [x] 之前网页一直在调整，文本内容是写在html里的，现在基本定型可以考虑抽离出来了； 原型地址：https://github.com/wuhan2020/design-prototype
2. [ ] 我将评委的数据建立起来了，其他的合作平台之类的数据也应该抽离出 datasource；
3. [x] 转换成react；
4. [ ] 手机端适配
5. [x] 将文字放入i18n 配置文件中

目前的页面：https://community.wuhan2020.org.cn/zh-cn/hackathon/index.html
老的issue：https://github.com/wuhan2020/wuhan2020.github.io/issues/238

**Comment by zhaofeng-shu33** [comment]
The speaker data has been extracted https://github.com/zhaofeng-shu33/wuhan2020.github.io/blob/23a18ca690c5f8338e54bbad31328055d7e1caa9/src/pages/hackathon/index.jsx#L39.

**Comment by zhaofeng-shu33** [comment]
I have moved the speaker data to `/i18n/zh-cn.js`.

**Comment by zhaofeng-shu33** [comment]
@jeremy0519 Can you help to resolve this issue by translating `/i18n/en-us.js` from `/i18n/zh-cn.js`  for hackathon part ?

**Comment by zhaofeng-shu33** [comment]
@lovepoem Where is the data of judge?

**Comment by lovepoem** [comment]
> @lovepoem Where is the data of judge?

@namaste Do you know about this ?

**Comment by jeremy0519** [comment]
是把zh-cn.js里面hackathon部分的英文翻译成中文吗？

**Comment by jeremy0519** [comment]
speaker list里面基本是英文

**Comment by jeremy0519** [comment]
@zhaofeng-shu33

**Comment by zhaofeng-shu33** [comment]
No need to translate English into Chinese I think. There are some Chinese texts in the dictionary of hackathon. We can translate them into English first.

**Comment by jeremy0519** [comment]
What does "them" refer to?

**Comment by zhaofeng-shu33** [comment]
the empty string in hackathon of en-us.js

**Comment by jeremy0519** [comment]
You can review the pr mentioned above.

**Comment by jeremy0519** [comment]
Also update the subject, activity, holder, application section.

**Comment by zhaofeng-shu33** [comment]
That's true

**Comment by AnnaCICI** [comment]
> Also update the subject, activity, holder, application section.

Hello @jeremy0519 ,

 @zhaofeng-shu33 told me that maybe you need help, please let me know if you want me to translate certain sections.

**Comment by lynklody** [comment]
Jr React developer & EN-CN translator. At your service.

**Comment by zhaofeng-shu33** [comment]
What do you mean @lynklody

**Comment by lovepoem** [comment]
暂时关闭，没有完成的工作，可以重新建立issue
