### ISSUE TITLE
[Hack for Wuhan] Hack for wuhan Hackathon is waiting for you!

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#316]
[Original Link](https://mp.weixin.qq.com/s/r9QKAV04yQzCis84XtjnCA)

# Hack for Wuhan Hackathon is waiting for you!

![img](https://mmbiz.qpic.cn/mmbiz_jpg/32JAxM2rtQGibVjGaFytTqfPFfZzpocBasESR3NI3BOtBdWzCsZ8r6cFq9lv8GpDN9ibx1ZVPVG2hxEWWicroT8jA/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1)

> In the face of the oubreak of COVID-19, an individual is small and powerless. The sudden emergence of the new coronavirus has made us realize that even in this developed society, human beings as a species is vulnerable, let alone an individual.
>
> 
>
> In The Tale of Two Cities, Dickinson writes his most famous quote: "It was the best of times, it was the worst of times." But no matter what the time has told us about, one thing will never change: this is *our* time.
>
> No one is born a hero. Under the protecting clothes are flesh and blood just like us, and behind the 14 days of construction of  *Huoshenshan Hospital* and *Leishenshan Hospital* are workers with their arduous work and the sense of responsibility. 

## 01. What can we do?

As of 22:00 on February 22, 2020, a total of 77,924 cases of nCov infected have been confirmed worldwide,  2,362 died. In a crisis, how can we, as ordinary people, participate in such a battle?

![img](https://mmbiz.qpic.cn/mmbiz_png/32JAxM2rtQEEufaKMDDK9OJMyUjicJmWY0MC52Vob5uvRABWELJIrY3ic3Z2ohkNibDW4UUWRDnDhmxkgTvDnhpPA/640?wx_fmt=png&wxfrom=5&wx_lazy=1&wx_co=1)

[As of 2pm, Feb 22nd, China has confirmed 52,973 cases of infected by the coronovirus]

If you are worried about the changing number of cases,  you can't find directions on the resumption date that is postponed again and again, or you feel lost because you are not able to buy masks and vegetables, you may wish to finish reading our story.

"We have been thinking about how to make use of the open source collaboration model to efficiently extend our help to the people in need." Wu Xue said, a man from Wuhan currently working in Silicon Valley, 

![img](https://mmbiz.qpic.cn/mmbiz_png/32JAxM2rtQEEufaKMDDK9OJMyUjicJmWYDmmnKYmtDzs7gNk8zEQibHib9nibUbpXzBb27yv5dMmllRdESKvqqXI5w/640?wx_fmt=png&wxfrom=5&wx_lazy=1&wx_co=1)

[Xue Wu]

[From Wuhan / Working in Silicon Valley / Business leader of a well-known communication company / Wuhan2020 open source community volunteer / The founder of *Hack for Wuhan* / Passion for entrepreneurial innovation and value creation]

"I want to find the essence of continuous innovation from my dream school." At Stanford, he studied the relationship between collaboration and innovation, and applied what he learned to industrial digitalization and AI transformation.

Many hospitals quickly ran out of supplies as the virus attacked Wuhan. Wu Xue, who is deeply attached to his hometown Wuhan, decided to use his expertise to build the bridge from potential suppliers to the hospitals in desperate need.

## 02. Connected to solve the problem

Wu Xue recalled, "I have experienced SARS, and I paid close attention to this epidemic as soon as it became apparent. Unfortunately, the outbreak still happened."

"I have family and classmates working in the hospital. I heard them asking for help at the time, and I felt that the hospitals began overloaded with patients in a very short period of time, and their masks could not cope with the surge in demand."

"And rumors has it that some people could not be delivered directly to the designated hospital, and some medical supplies are detained. So our team decided to use the simplest way deliver the resources."

" It is quite easy to connect people and build trust in the Silicon Valley. By collaboration, we can solve huge problems quickly and accurately."

![img](https://mmbiz.qpic.cn/mmbiz_png/32JAxM2rtQEEufaKMDDK9OJMyUjicJmWYjhI0eFHhWISROD9ibaYWDsbC15SrafxFibAH80ls8fKfYSzbauial8aDQ/640?wx_fmt=png&wxfrom=5&wx_lazy=1&wx_co=1)

[The figure above compares the density of interconnected entrepreneurs in Silicon Valley, Boston, and the rest of the United States. Boston on the left and Silicon Valley on the second.]

[Source | T. D. Zoller, The Dealmaker Milieu: The Anatomy of Social Capital in Entrepreneurial Economies, Doctoral Dissertation,University of North Carolina at Chapel Hill, NC, 2010.]

He persuaded a medical business partner within an hour, and quickly met a startup company through them. They formed a team, and then docked with volunteers in China to understand the specific needs.

In this way, a precise donation platform was set up, where the demands was passed to the donor side in real time, and the donors can directly send the resource to the doctors in the hospital.

==Troublesome==

> 他完成了一个协同创造价值的过程
> Through this little practice, he has completed a collaborative v , and this is precisely the essence of a open source collaboration: lighting up his own light, thereby driving a greater light, so that value and resources can be connected Was reasonably used.

## 03. A group of people and a community

At the same time, Wu Xue also joined the Wuhan2020 open source community and met more partners with the same goal.

Wuhan2020 is an open source community platform launched by a group of enthusiastic developers since January 2020.

==Put an English page pic here==

![img](https://mmbiz.qpic.cn/mmbiz_png/32JAxM2rtQHp9kBY832hbYtXwIjHG74KZcOy17ibroRr75MJWUM8wLRb9n3GDJLHTHG0098t0zT7B6nvmUibnYtQ/640?wx_fmt=png&wxfrom=5&wx_lazy=1&wx_co=1)

[Wuhan2020 Community HomePage]

[URL: https://community.Wuhan2020.org.cn/]

Volunteers collect information about hospitals, hotels, factories, logistic companies, donations, virus prevention and treatment, and epidemic dynamics. They collect and post the information in the same platform to bridge the gap of information asymmetry, thus help efficiently allocate resource from across the globe.

During the donation process, Wu Xue spent almost 80% of the time to collect and verify the authenticity of the information. "I asked the founder of Wuhan2020 about the process of information collection and verification process, and then shared my previous lessons to them, hoping that other volunteers would not take a detour.”

The volunteers in Wuhan2020 quickly adopted the suggestion and optimized the platform. and the following things also proved the value of everyone's collaboration:

Docking and verifying the needs of Wuhan Tongji, Zhongnan and other hospitals; donating N95 masks by Chinese companies in the United States; providing full digital traceability logistics technology in Silicon Valley startups, and helping deliver masks to doctors as soon as possible.

![img](https://mmbiz.qpic.cn/mmbiz_jpg/32JAxM2rtQEEufaKMDDK9OJMyUjicJmWYpQk6XgY6BIKMkJradTJdUGVicIK2Y0m0kliba5M8iaGSnib1XaHWvNda1Q/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1)

[ Gliding Eagle - Final check before the shipping of the medical supply]

Not only that, he also actively assisted a number of volunteer teams, including the Oxford Cambridge Alumni Assistance Association, to dock frontline demand data to the Wuhan2020 platform.

Furthermore, it attracted BUTTON and its global medical cross-border business development platform to fight against the virus, which also helped successfully bridged to several Nordic suppliers and their hundred thousand dollar worth medical supplies.

![img](https://mmbiz.qpic.cn/mmbiz_png/32JAxM2rtQEEufaKMDDK9OJMyUjicJmWYUJRJujbyVDDje7RUlibOgGTM1fdDRHOnAD0WamucQtSH18BuI24kmjw/640?wx_fmt=png&wxfrom=5&wx_lazy=1&wx_co=1)

[BUTTON: Global anti-2019-nCoV Consortium]

[Source of Data: Wuhan2020]

![img](https://mmbiz.qpic.cn/mmbiz_png/32JAxM2rtQGibVjGaFytTqfPFfZzpocBaLN7yBSBZr6LVvFv18fVBXYwZLYaeyqJUd5PzqEziagUMG6yicBiauiaoiaw/640?wx_fmt=png&wxfrom=5&wx_lazy=1&wx_co=1)

[Medical supplies from the suppliers in Sweden]

In Wu Xue's view, Wuhan2020 is not only an online infrastructure that connects information islands, but also a platform for creating shared value.

The entire project connects more than 3,000 volunteers across the globe, including software developers, product managers, designers, data analysts, information collectors, translators, media workers, and students. The diverse team helped maximize the use and transmission of information in the race against time. 

Wuhan2020 also established a community that values trust, transparency, and technology. Its Github repo has received over 6,000 stars.

## 04. Next stop: Hackathon

But all this is just the beginning.

Now, Wu Xue and the volunteers in Wuhan2020 is preparing for the great hackathon - Hack for wuhan, trying to use another *geek movement* to get more people to join the battle against the epidemic.

![img](https://mmbiz.qpic.cn/mmbiz_jpg/32JAxM2rtQGibVjGaFytTqfPFfZzpocBasNEFw996scicfjHbdlKtIy8ibeUD8ibce8bDhA0OWSHZUKEPWN3q5rrbw/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1)

This event will be conducted in the form of an online hackathon, and participants will be encouraged to seek solutions to public crises and social challenges in three days in a team-based manner, bringing their ideas to reality.

They call for more people to propose innovative projects and use the power of open source collaboration to help fight the epidemic. The hackathon also establish better connections between volunteers, institutions, businesses and other platforms.

Everything will be welcomed here — radical designs, prototypes, business idea, or social work. Once we connect the world as a whole, we will know that there is no shortage of resources. What is lacking is to make distributed resources work synergistically through the transparent flow of information, and everyone can be a part of it.

"Online hacking is more than just submitting code. We will try to facilitate inclusive communication for developers, product managers, venture capital leaders, students and people from academia." Hack For Wuhan got the investment from *Run The World*, an online event platform based in Silicon Valley. This will give participants an opportunity to know each other and have a new collaborative experience.

Regarding this opening of hackathon, Wu Xue hope that friends from all over the world will be invited to participate in this new collaborative movement. He also stated that "whatever you come from, I will try my best to let you feel you have accomplished something and feel proud within the community.”

![img](https://mmbiz.qpic.cn/mmbiz_jpg/32JAxM2rtQGibVjGaFytTqfPFfZzpocBaaLRiaxfzCbEtnEdTMPr4ZPz31mjfO5oQ77woPNVJPib4a7CLIbRPZ30g/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1)

"If you have technology or ideas, we will provide you with a stage for show case; if you are enthusiastic about charity, we will provide implementable technologies and ideas; if you have a passion, we will take you to experience the power of open source collaboration and realize your potential."

Professional guidance in the event is also highly valued. Wu Xue said, "In Stanford's entrepreneurship class, the most frequently asked questions by mentors are: What have you learnt? What could you do better?” 

Hack for wuhan has obtained the recognition of many well-known institutions, inviting a number of heavyweight guests. Among the team of tutors are scholars from Stanford, Berkeley, MIT and other famous universities, and the team of tutors is still growing.

==Check the company names here==

There are also top VCs such as Andreessen Horowitz, Sequoia, Zhenge Fund, Jinshajiang Venture Capital, Google, Microsoft, Alibaba Cloud, Byte Dance, Facebook, Pinterest, Uber, Didi and other big companies.

There are also outstanding startups such as Polarr, Gliding Eagle, Vigo, Scale AI, covariant.ai, Run The World, and many guests from top law firm Wilson Sonsini.

## 05. Come and join us!

Maybe - you don’t have the ability to directly save and help the infected. But the aggregation of many small ideas can make a big differece. Wu Xue and his friends had proven by their own experiences, and they are welcoming you to join the fight.

What are you waiting for?

You can scan the QR code below, or click to read the original text to enter the hack for wuhan registration direct page. Welcome you, and I hope you can forward it to more friends!

![img](https://mmbiz.qpic.cn/mmbiz_jpg/32JAxM2rtQGibVjGaFytTqfPFfZzpocBawQRjm9mgtG3EhGMYZzFhAlCD2tWssa7MycZic0WhQc6ibs6pmxwJ4ddw/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1)

**Comment by GindaChen** [comment]
To reviewer

1. The translation of the following sentence is pretty hard.
> 通过这次小小的实践，他完成了一个协同创造价值的过程，而这恰恰也是开源协作方式的精髓：点亮属于自己的光，从而带动出更大的光芒，让价值和资源能够在连接中被合理的利用。

2. The company namaes needs verification (marked as `==Check the company names here==`)

There are also top VCs such as Andreessen Horowitz, Sequoia, Zhenge Fund, Jinshajiang Venture Capital, Google, Microsoft, Alibaba Cloud, Byte Dance, Facebook, Pinterest, Uber, Didi and other big companies.

There are also outstanding startups such as Polarr, Gliding Eagle, Vigo, Scale AI, covariant.ai, Run The World, and many guests from top law firm Wilson Sonsini.



3.

**Comment by GindaChen** [comment]
[translation.md.zip](https://github.com/wuhan2020/wuhan2020.github.io/files/4265113/translation.md.zip)

**Comment by jeremy0519** [comment]
先把what can we do的第一句话nCov改成COVID-19

**Comment by lovepoem** [comment]
@GindaChen Would you please pull a request ?

**Comment by HelloKittyHacker** [comment]
Wow that's incredible!!

**Comment by lovepoem** [comment]
暂时关闭，有问题随时打开
