### ISSUE TITLE
remove generate file in build directory

### ISSUE THREAD

**Issue by zhaofeng-shu33** [wuhan2020/wuhan2020.github.io#323]
## 描述功能要求
remove generate file
### 如果有的话，请附图
Such as `build` directory

**Comment by frank-zsy** [comment]
Agree, auto generated files should not be included.

**Comment by iLtc** [comment]
I agree that the build folder should be removed.

**Comment by lovepoem** [comment]
可以尝试下。我记得有点问题，这个build下的东西删掉的话。

**Comment by zhaofeng-shu33** [comment]
OK
