### ISSUE TITLE
Add temporary preview in CI

### ISSUE THREAD

**Issue by zhaofeng-shu33** [wuhan2020/wuhan2020.github.io#331]
## 描述功能要求
Currently, the build of pr does not produce artifact. Some contributors are unable to have the local build environment and we are not sure whether their changes are ok. This is especially true for changes in style-sheets. So can we provide a way to download the artifacts for pr build?

**Comment by lovepoem** [comment]
@purple-force Would you give some advice ?

**Comment by lynklody** [comment]
Don't quite know how this works, but I've seen some Github projects using CircleCI and it's compeletely compatible with github: https://circleci.com/integrations/github/. Just FYI.

**Comment by zhaofeng-shu33** [comment]
You can check [artifacts](https://github.com/wuhan2020/wuhan2020.github.io/actions/runs/49891734) for example. GitHub Actions is similar to CircleCI. Both of them have artifacts functionality.

**Comment by jeremy0519** [comment]
How about [netlify](https://netlify.com)?

**Comment by zhaofeng-shu33** [comment]
Maybe this feature is not needed any more. You can close it.

**Comment by jeremy0519** [comment]
I think it may be needed. For example, the comment box can be previewed.

**Comment by iLtc** [comment]
我给咱们的站点挂了 Netlify，现在每个 PR 都会生成一个预览，效果如图：

![image](https://user-images.githubusercontent.com/4352234/77278321-73fb5700-6c95-11ea-83a3-f0e9ab463c4d.png)

点 1 可以看到那些页面发生了变化，点 2 可以看预览站点。

Netlify 免费账户有 300 分钟的 build 时间，咱们先用着，满意的话后面可以加入他们的开源项目计划。

**Comment by jeremy0519** [comment]
@iLtc Can you share the domain?

**Comment by iLtc** [comment]
@jeremy0519 

The domain is different for each PR since it contains the issue id: https://deploy-preview-[ISSUE ID]--reverent-lumiere-ad26e3.netlify.com/.

You can see the specific link for each PR on the PR page.

You can check #497 for example.
