### ISSUE TITLE
English homepage menu not expand on pc

### ISSUE THREAD

**Issue by zhaofeng-shu33** [wuhan2020/wuhan2020.github.io#347]
## 当前问题
请描述清楚你使用的环境，最好有相应的截图以便我们重现问题
![image](https://user-images.githubusercontent.com/23316477/75844359-b2c58c00-5e10-11ea-90bc-5acd5a03ddd9.png)

## 期待的正确输出
![image](https://user-images.githubusercontent.com/23316477/75844391-ca9d1000-5e10-11ea-8c3e-80b2f106096e.png)

**Comment by lovepoem** [comment]
可能是网络问题，现在不能重现
