### ISSUE TITLE
Slack Channel List Page

### ISSUE THREAD

**Issue by lynklody** [wuhan2020/wuhan2020.github.io#358]
## 描述功能要求

Since our dev team chat moved from Slack to Lark, should we modify the slack channel list page and its content https://community.wuhan2020.org.cn/zh-cn/docs/dev/slack-channels.html into what we have on Lark?

**Comment by zhaofeng-shu33** [comment]
I do not think we need. Very few people use Lark now.

**Comment by lynklody** [comment]
Ok
