### ISSUE TITLE
Speakers session on the hackathon page (zh-cn) is still in English

### ISSUE THREAD

**Issue by lynklody** [wuhan2020/wuhan2020.github.io#365]
## 描述你需要修改或新增的文档
It seems the source code's under /utils/zh-cn/hackathon/index.html and the the content is hard-coded. The previous part on the page is already coded in Chinese. However, the speaker portion is still in English. Is it necessary to parameter the data or should the hard-coded portion be converted to Chinese without modifying the code?

### 如果有的话，请附图
![image](https://user-images.githubusercontent.com/22569999/75974348-93faee80-5f11-11ea-92ea-8d7c5c7ab5ee.png)

**Comment by zhaofeng-shu33** [comment]
No, please see `src/pages/hackathon/index.jsx` instead. It is not hard-coded.
Indeed, there is no Chinese introduction of speakers. But I do not think it is a big problem

**Comment by lynklody** [comment]
I didn't find the path```src/pages/Hackathon/hackathon.jsx```
Is the gitee repo version outdated?

**Comment by zhaofeng-shu33** [comment]
I have updated the path.

**Comment by lynklody** [comment]
I don't see hackathon directory under ```src/pages/```.
Source code cloned from Gitee. Is the Gitee repo not synced with the Githun one?

**Comment by JCCC001** [comment]
I will solve it

**Comment by zhaofeng-shu33** [comment]
Please check out to `dev` branch, the master branch is generated from `dev`. @lynklody

**Comment by lynklody** [comment]
@zhaofeng-shu33 Got it. Thanks!

**Comment by zhaofeng-shu33** [comment]
See PR #369

**Comment by lovepoem** [comment]
Closed via https://github.com/wuhan2020/wuhan2020.github.io/pull/369
