### ISSUE TITLE
黑客松赛程看板-前端

### ISSUE THREAD

**Issue by katejia110** [wuhan2020/wuhan2020.github.io#375]
设计：https://www.figma.com/file/kApXTHeEBwJIrqAyvSv6rc/Hackathon?node-id=85%3A108 
电脑和手机版本都在里面了。 

目前静态文件同步到了github：https://github.com/wuhan2020/design-prototype/tree/master/hackathonKanban
页面是黑客松的赛程看板数据请和 @frank-zsy  合作完成数据同步。

**Comment by lovepoem** [comment]
项目已经结束
