### ISSUE TITLE
kanban-Timer

### ISSUE THREAD

**Issue by pengcc** [wuhan2020/wuhan2020.github.io#376]
## 描述功能要求
- In Page hackathonKanban
- mobile-first
- functional component no state, name: KanbanTimer
- props: title [string], from[time string], timeSlots[array of object]
### 如果有的话，请附图
-- current feature----
**显示过了北京时间3月6号凌晨12点多久**
![Screenshot 2020-03-06 at 12 37 33](https://user-images.githubusercontent.com/10584406/76080479-429d3e80-5fa7-11ea-86d7-acddc08defb8.png)

----old feature-----
![Screenshot 2020-03-06 at 11 50 24](https://user-images.githubusercontent.com/10584406/76077691-80976400-5fa1-11ea-8ba4-22642537b028.png)

## 额外的信息
 完整设计看https://www.figma.com/file/kApXTHeEBwJIrqAyvSv6rc/Hackathon?node-id=85%3A109

**Comment by zhaofeng-shu33** [comment]
which `url`?

**Comment by pengcc** [comment]
Currently, the timer can only show static time. I reopen the bug and fix it soon.

**Comment by pengcc** [comment]
pr not working here, separate pr created. This issue closed.

**Comment by zhaofeng-shu33** [comment]
![image](https://user-images.githubusercontent.com/23316477/76143357-b75c9f80-60b1-11ea-8749-6d9483166174.png)
