### ISSUE TITLE
Kanban-BadgeCardList

### ISSUE THREAD

**Issue by pengcc** [wuhan2020/wuhan2020.github.io#377]
## 描述功能要求
- In page hackathonKanban
- mobile-first
- component name: BadgeCardList
- props: itemList [array]

### 如果有的话，请附图

![Screenshot 2020-03-06 at 11 50 37](https://user-images.githubusercontent.com/10584406/76078625-5777d300-5fa3-11ea-8760-638843b0a978.png)

![Screenshot 2020-03-06 at 11 50 57](https://user-images.githubusercontent.com/10584406/76078639-5cd51d80-5fa3-11ea-93a6-c00263687649.png)

## 额外的信息
see the design  https://www.figma.com/file/kApXTHeEBwJIrqAyvSv6rc/Hackathon?node-id=85%3A109

**Comment by lovepoem** [comment]
已经完成
