### ISSUE TITLE
kanban-hackathonProgress

### ISSUE THREAD

**Issue by pengcc** [wuhan2020/wuhan2020.github.io#379]
## 描述功能要求
- In page hackathonKanban
- mobile-first, please consider the difference between mobile and desktop
- functional component state, name: HackathonProgress
- props: title [string], timeStart[time string], timeEnd[time string], milestone[object]
### 如果有的话，请附图
[mobile]
![Screenshot 2020-03-06 at 11 51 12](https://user-images.githubusercontent.com/10584406/76079735-9c9d0480-5fa5-11ea-98f3-17f07fb1ec8f.png)

[desktop]
![Screenshot 2020-03-06 at 12 25 16](https://user-images.githubusercontent.com/10584406/76079705-8b53f800-5fa5-11ea-8308-30c80bba1597.png)

## 额外的信息
see the design
https://www.figma.com/file/kApXTHeEBwJIrqAyvSv6rc/Hackathon?node-id=0%3A1

**Comment by lovepoem** [comment]
已经完成
