### ISSUE TITLE
Kanban-dark mode

### ISSUE THREAD

**Issue by pengcc** [wuhan2020/wuhan2020.github.io#384]
## 描述功能要求
- add a mode toggle button- change page background color
- Click the button to toggle normal mode or dark mode
### 如果有的话，请附图
![Screenshot 2020-03-06 at 13 02 39](https://user-images.githubusercontent.com/10584406/76082053-c60c5f00-5faa-11ea-871e-7d0b30a08e8c.png)
## 额外的信息
see the design
https://www.figma.com/file/kApXTHeEBwJIrqAyvSv6rc/Hackathon?node-id=0%3A1

**Comment by lovepoem** [comment]
这个不用实现
