### ISSUE TITLE
Kanban-TeamListPaging

### ISSUE THREAD

**Issue by pengcc** [wuhan2020/wuhan2020.github.io#385]
## 描述功能要求
- In page hackathonKanban
- mobile-first, please consider the difference between mobile and desktop

### 如果有的话，请附图
![Screenshot 2020-03-06 at 13 11 03](https://user-images.githubusercontent.com/10584406/76082542-f1dc1480-5fab-11ea-958a-d10767c43719.png)

**Comment by lovepoem** [comment]
全部显示好了
