### ISSUE TITLE
feat: 把主题色蓝色（#1890ff ）改成#ff6440

### ISSUE THREAD

**Issue by damingerdai** [wuhan2020/wuhan2020.github.io#39]
### 需求：统一产品风格：
把主题色蓝色（#1890ff ）改成#ff6440

### 来源
[wuhan2020/issues/292](https://github.com/wuhan2020/wuhan2020/issues/292)

### 说明
实际的主题颜色应该是： #0054D1

**Comment by iLtc** [comment]
请问这个 issue 只需要修改主题颜色吗？原始 issue 中的修改 logo 和添加插画需要完成吗？

**Comment by damingerdai** [comment]
个人认为是需要的，但是我联系不到设计师

**Comment by iLtc** [comment]
那我也试着去联系一下 kate Jia

**Comment by iLtc** [comment]
我拿到插画了，还在等设计师的logo

**Comment by lovepoem** [comment]
可以小步快跑，拆分pr，只修改一部分就pr 一部分

**Comment by damingerdai** [comment]
我在上班，@iLtc，你先做吧

**Comment by iLtc** [comment]
这个 issue 还差几个部分：

1. 首页左上角的 logo 需要替换，在等设计师的图片
2. 二级页面顶部的主题色也需要修改，但由于是渐变色，在等待设计师确认具体色号
