### ISSUE TITLE
图片，无法显示

### ISSUE THREAD

**Issue by aefgijn** [wuhan2020/wuhan2020.github.io#4]
建议图片放在图床上 ，例如：腾讯云等

**Comment by lovepoem** [comment]
目前github上的图片，国内确实显示有一点问题

**Comment by lovepoem** [comment]
你可以pr 一下么？ @aefgijn

**Comment by chenrui333** [comment]
图片问题应该在最近几个 PR 里面解决了。

relates to #33 #29 

Closing the issue now, feel free to open a new one if needed.
