### ISSUE TITLE
Kanban - 将入围决赛团队和最终获奖团队加上勋章

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#408]
## 描述功能要求
Kanban - 将入围决赛团队和最终获奖团队加上勋章

https://community.wuhan2020.org.cn/zh-cn/hackathonKanban/index.html
![image](https://user-images.githubusercontent.com/827112/76413675-cce30980-63d0-11ea-880f-9221b4d72ee3.png)

因为已经有初赛项目列表了，所以，直接初赛项目的每个section  打上类似于勋章的标签，并加上所获奖项的文字 
文字有： 一等奖、二等奖、三等奖、观众最喜爱、导师最喜爱、入围决赛

决赛10强
2 Aid Tracker捐赠直连——捐赠对接与追踪一体化平台  
4 高校健康打卡平台 
6 DiagnoseMe 
12 中医AI诊断系统 
14 Nedelp 设计 联名 众筹 
15 一站式疫情数据开放平台   
20 Predication + Notification 
22 疫情智能机器人-小源  
25 翔鹰验收   
26 疫情故事商店 
30 City Hero 
37 autovax

获奖名单：

一等奖 First Prize：
15 一站式疫情数据开放平台

二等奖 Second Prize：
37autovax  
30 City Hero  

三等奖 Third Prize:
25 翔鹰验收   
2 Aid Tracker捐赠直连  
20 Predication + Notification
(各 4000 元人民币云开发资源）

观众最喜欢项目奖 Audience Favorite Award：
4 高校健康打卡平台 

导师最喜欢项目奖 Judges Favorite Award：
22 疫情智能机器人-小源

**Comment by lovepoem** [comment]
![mmexport1583624960811](https://user-images.githubusercontent.com/827112/76154093-7ac09080-6111-11ea-8d8b-ee58044c6ef2.jpg)
数据桩子已经有了

**Comment by lovepoem** [comment]
![mmexport1583626109719](https://user-images.githubusercontent.com/827112/76154247-0d622f00-6114-11ea-8b8d-abfb85b42137.jpg)

**Comment by evaqy** [comment]
Hello, lovepoem! 我是这个页面的设计师。卡片上的奖项已经做好了，具体可以看figma文件里的。

另外，卡片是鼠标悬停后才会显示项目内容，与黑客松页面上，评委和演讲人卡片的效果一样：
https://community.wuhan2020.org.cn/zh-cn/hackathon/index.html

<img width="1001" alt="Screen Shot 2020-03-11 at 6 25 27 PM" src="https://user-images.githubusercontent.com/35118281/76470002-efbbf080-63c5-11ea-9705-8a403a578951.png">

谢谢啦~

**Comment by lovepoem** [comment]
> Hello, lovepoem! 我是这个页面的设计师。卡片上的奖项已经做好了，具体可以看figma文件里的。
> 
> 另外，卡片是鼠标悬停后才会显示项目内容，与黑客松页面上，评委和演讲人卡片的效果一样：
> https://community.wuhan2020.org.cn/zh-cn/hackathon/index.html
> 
> <img alt="Screen Shot 2020-03-11 at 6 25 27 PM" width="1001" src="https://user-images.githubusercontent.com/35118281/76470002-efbbf080-63c5-11ea-9705-8a403a578951.png">
> 
> 谢谢啦~

太感谢了！！！
> 卡片是鼠标悬停后才会显示项目内容，与黑客松页面上，评委和演讲人卡片的效果一样

@pengcc 麻烦看一下
