### ISSUE TITLE
kanban timeline broken and deprecated date format

### ISSUE THREAD

**Issue by pengcc** [wuhan2020/wuhan2020.github.io#425]
## 当前问题
请描述清楚你使用的环境，最好有相应的截图以便我们重现问题
![Screenshot 2020-03-11 at 09 11 09](https://user-images.githubusercontent.com/10584406/76395745-469ad900-6378-11ea-843b-ad3f361d8ed2.png)
![Screenshot 2020-03-11 at 09 08 15](https://user-images.githubusercontent.com/10584406/76395753-48fd3300-6378-11ea-9d44-101284b33117.png)

**Comment by zhaofeng-shu33** [comment]
the timeline is broken?

**Comment by pengcc** [comment]
> the timeline is broken?

a math calculation bug has been fixed

**Comment by zhaofeng-shu33** [comment]
ok, I will check it locally.
