### ISSUE TITLE
Review the translations for it-it and ja-jp setup

### ISSUE THREAD

**Issue by chenrui333** [wuhan2020/wuhan2020.github.io#43]
For the time being, I have used Google Translate to translate the key pages. These translations need to be reviewed and re-translate if needed.

https://github.com/wuhan2020/wuhan2020.github.io/pull/41
https://github.com/wuhan2020/wuhan2020.github.io/pull/42
https://github.com/wuhan2020/wuhan2020.github.io/pull/27

**Comment by GindaChen** [comment]
Will soon coordinate the translation group to resolve this.

**Comment by chenrui333** [comment]
it-it review ticket, https://github.com/wuhan2020/wuhan2020.github.io/issues/68

**Comment by GindaChen** [comment]
ja-jp review ticket, #74
