### ISSUE TITLE
[Disucssion] Page content enhancement

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#44]
[Drafting...]

1. 应该在主页/显眼的地方加一个link到官方通稿。当前是一定要点到`博客`才能看到官方通稿
      1. 解决1: 在主页和什么是WHU2020更改一下能access到这个blog
      2. 解决2: 另外开一个tab做官方通稿
      3. 解决3: 直接放到主页的下方

2. Polish公告措辞：
   1. 项目**入口**：门户入口，GitHub入口，App入口--到底是哪个入口？
   2. （中文）公告的措辞可能可以让翻译组的朋友们也polish一下

3. 加一个About Us在首页

@Atena1118  @lovepoem @chenrui333 Any suggestions / insight will be appreciated.

**Comment by chenrui333** [comment]
加一个 banner？

**Comment by lovepoem** [comment]
我们官方首页被我删除了一些，看同模板的 http://dubbo.apache.org/zh-cn/

**Comment by lovepoem** [comment]
@purple-force 你有啥好的建议吗？

**Comment by lovepoem** [comment]
暂时关闭，有需求再打开
