### ISSUE TITLE
对于时钟组件，当过了这个时间段，时钟归零

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#441]
## 描述功能要求
对于时钟组件，应该有“开始时间”和“结束时间”属性，比如3-6至3-8，当过了这个时间段，时钟归零，见图片
### 如果有的话，请附图
![Screenshot_20200315_061339](https://user-images.githubusercontent.com/827112/76691289-50785100-6684-11ea-9216-a0cd815e26c6.jpg)

**Comment by pengcc** [comment]
currently displays the time after 2020-03-08. But this issue will be fixed.
