### ISSUE TITLE
本地docsite start 启动时候报env is not defined

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#442]
## 当前问题
请描述清楚你使用的环境，最好有相应的截图以便我们重现问题
![image](https://user-images.githubusercontent.com/827112/76698057-50567080-66d9-11ea-9348-38e07e7d6d66.png)

本地docsite start 启动时候报env is not defined

**Comment by zhaofeng-shu33** [comment]
Use `npm run start` instead?

**Comment by lovepoem** [comment]
> Use `npm run start` instead?

Have the same issue

**Comment by zhaofeng-shu33** [comment]
Uninstall docsite globally and run `npm run start` again?

**Comment by pengcc** [comment]
delete node modules and reinstall `npm i`. Check if env has been passed to template.ejs in node_modules/docsite/lib/generateHTMLFile.js and node_modules/docsite/lib/generateJSONFile.js.
```
ejs.renderFile(
        path.join(cwd, './template.ejs'),
        {
          title: getConfigValue(docsiteConfig, 'pages', 'home', lang, 'title') || 'home',
          keywords: getConfigValue(docsiteConfig, 'pages', 'home', lang, 'keywords') || 'home',
          description: getConfigValue(docsiteConfig, 'pages', 'home', lang, 'description') || 'home',
          rootPath: window.rootPath,
          page: 'home',
          __html: ReactDOMServer.renderToString(React.createElement(Page, { lang }, null)),
          env,
        },
```

**Comment by lovepoem** [comment]
> delete node modules and reinstall `npm i`. Check if env has been passed to template.ejs in node_modules/docsite/lib/generateHTMLFile.js and node_modules/docsite/lib/generateJSONFile.js.
> 
> ```
> ejs.renderFile(
>         path.join(cwd, './template.ejs'),
>         {
>           title: getConfigValue(docsiteConfig, 'pages', 'home', lang, 'title') || 'home',
>           keywords: getConfigValue(docsiteConfig, 'pages', 'home', lang, 'keywords') || 'home',
>           description: getConfigValue(docsiteConfig, 'pages', 'home', lang, 'description') || 'home',
>           rootPath: window.rootPath,
>           page: 'home',
>           __html: ReactDOMServer.renderToString(React.createElement(Page, { lang }, null)),
>           env,
>         },
> ```

Now it is ok, using this method
