### ISSUE TITLE
Add gitalk component

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#450]
## 描述功能要求

Add gitalk componet
在模板添加gitalk组件，使用github issues做为评论区

**Comment by jeremy0519** [comment]
需要github application

**Comment by lovepoem** [comment]
> 需要github application

这个不难

**Comment by jeremy0519** [comment]
> Use in React
Import the Gitalk with
`import GitalkComponent from "gitalk/dist/gitalk-component";`
And use the component like
> `<GitalkComponent options={{`
> `clientID: "...",`
> `clientSecret: 'GitHub Application Client Secret',`
>   `repo: 'GitHub repo',`
>  `owner: 'GitHub repo owner',`
  >`admin: ['GitHub repo owner and collaborators, only these guys can initialize github issues'],`
>  `id: location.pathname,      // Ensure uniqueness and length less than 50`
>  `distractionFreeMode: false  // Facebook-like distraction free mode`
>  `}} />`

**Comment by chenrui333** [comment]
我来弄弄

**Comment by chenrui333** [comment]
这个是不是 只能做一个 issue ?

**Comment by chenrui333** [comment]
@jeremy0519 `https://github.com/settings/applications/new` 可以在那里注册

**Comment by jeremy0519** [comment]
嗯

**Comment by jeremy0519** [comment]
应该可以每个页面一个issue

**Comment by chenrui333** [comment]
我直接加到 template.ejs 下面了的，你们看看

**Comment by jeremy0519** [comment]
那现在评论区在哪里啊？

**Comment by chenrui333** [comment]
好像不太 work。

**Comment by jeremy0519** [comment]
是不是要在`src/pags/documention/index.jsx`里面加上

**Comment by chenrui333** [comment]
你可以试一试

**Comment by jeremy0519** [comment]
先试一下documention

**Comment by jeremy0519** [comment]
deploy不行，好像要先安装gitalk，要在package.json里面加上

**Comment by jeremy0519** [comment]
要用npm安装

**Comment by jeremy0519** [comment]
应该还要import
`import 'gitalk/dist/gitalk.css'`
`import Gitalk from 'gitalk'`

**Comment by jeremy0519** [comment]
deploy还是不行

**Comment by jeremy0519** [comment]
How about using [valine](https://valine.js.org)?

**Comment by lovepoem** [comment]
> How about using [valine](https://valine.js.org)?

先去除所有和gitalk相关的提交，等本地测试通过再提交

**Comment by lovepoem** [comment]
还有一个问题，是不是得重新建立一个项目作为评论区的存储。为了和真正的bug,.issue分开？

**Comment by jeremy0519** [comment]
gitalk会把每个issue加上gitalk的标签

> 还有一个问题，是不是得重新建立一个项目作为评论区的存储。为了和真正的bug,.issue分开？

**Comment by jeremy0519** [comment]
还有gitalk必须要有github账号才能评论

**Comment by lovepoem** [comment]
> 还有gitalk必须要有github账号才能评论

嗯 开源社区嘛，那就申请吧
