### ISSUE TITLE
Hack for Wuhan - 将决赛视频在官网展示

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#468]
## 描述功能要求

Kack for Wuan - 决赛视频处理与展示

决赛积累了不少视频材料，初步设想:

1，将视频进行处理，打上社区标识
2，后端服务做存储与流媒体展示服务
3，官网前端进行展示

**Comment by nwljy** [comment]
如果有腾讯云或者阿里云，用cos加直播，批量上传视频到cos，调用即可，h5页面调用js，如果red5服务器二次开发

**Comment by lovepoem** [comment]
重复https://github.com/wuhan2020/wuhan2020.github.io/issues/467
