### ISSUE TITLE
[bug]首页颜色的交互有问题：拉到最下面后，应该是实现白色

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#48]
参考：https://wuhan2020.github.io/zh-cn/docs/overview/what-is-wuhan2020.html

![image](https://user-images.githubusercontent.com/827112/73624131-98b25580-467a-11ea-9c02-fed4b5b7a6ad.png)

首页颜色的交互有问题：拉到最下面后，应该是实现白色
现在都是橘红色

**Comment by lovepoem** [comment]
@iLtc  请看一下

**Comment by lovepoem** [comment]
![image](https://user-images.githubusercontent.com/827112/73624302-4de50d80-467b-11ea-8d91-d67fa9289cf4.png)

**Comment by iLtc** [comment]
![image](https://user-images.githubusercontent.com/4352234/73624425-adf19a80-460e-11ea-9026-a74d6d3292a1.png)

我这边无法复现这个问题哎，刷新一下还是这样吗？

**Comment by lovepoem** [comment]
嗯 是我这网速问题，没有这个问题。


麻烦你也把后面几个频道的头部颜色给修改成统一的

**Comment by iLtc** [comment]
后面几个频道的头部颜色是渐变色，我还在等设计师确认渐变色的具体数值

如果急的话我可以先改成纯色的

**Comment by lovepoem** [comment]
请向我邮箱发一封邮件，联系上我
