### ISSUE TITLE
添加"招聘汇" 模块，方便企业发布招人信息

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#504]
## 描述功能要求

1、添加"招聘汇" 模块，方便企业发布招人信息。
2、用人方直接利用原有的gitalk评论发布，应聘者可以评论回复
3、我们是一个因为危机事件而发起的社区，社区人员构成比较复杂。需要讲一下我们社区的基本人员构成，方便用人方贴信息。

**Comment by yangli-os** [comment]
社区基本人员构成：75%技术；%5的翻译人员；5%的产品经理；2.5%的协调、管理；1%风控和法务；5%宣传；5%信息录入；1.5%其他。

**Comment by tjob-slack** [comment]
可否指导一下，如何操作？ 
比如：要求什么工具，接口，如何发布代码。

**Comment by tjob-slack** [comment]
数据字典：
需求单位
需求岗位
任职资格
技能要求
工作职责描述
工作待遇
工作上下级汇报关系
单位介绍
需求人数
有效日期
申请日期
完成日期

**Comment by iLtc** [comment]
我之前看到一个社区发布流程是这样的，供参考：

1. 用人方通过提 issue 的方式来申请发布职位，issue 我们可以做个模版，包括 @tjob-slack 提出的这些字段

2. 我们审核 issue，完善细节

3. approve 之后由 bot 把 issue 复制到某个目录下，然后编译成招聘页面

**Comment by tjob-slack** [comment]
> 我之前看到一个社区发布流程是这样的，供参考：
> 
> 1. 用人方通过提 issue 的方式来申请发布职位，issue 我们可以做个模版，包括 @tjob-slack 提出的这些字段
> 2. 我们审核 issue，完善细节
> 3. approve 之后由 bot 把 issue 复制到某个目录下，然后编译成招聘页面

请问“编译成页面” 这步具体怎么实现呢？

**Comment by tjob-slack** [comment]
> ## 描述功能要求
> 1、添加"招聘汇" 模块，方便企业发布招人信息。
> 2、用人方直接利用原有的gitalk评论发布，应聘者可以评论回复
> 3、我们是一个因为危机事件而发起的社区，社区人员构成比较复杂。需要讲一下我们社区的基本人员构成，方便用人方贴信息。

 @iLtc 说的issue模版，和 @16647615268 你说的gitalk，不知道是不是一样的？

**Comment by lovepoem** [comment]
其实我还没有想好审核流程

**Comment by lovepoem** [comment]
> 我之前看到一个社区发布流程是这样的，供参考：
> 
> 1. 用人方通过提 issue 的方式来申请发布职位，issue 我们可以做个模版，包括 @tjob-slack 提出的这些字段
> 2. 我们审核 issue，完善细节
> 3. approve 之后由 bot 把 issue 复制到某个目录下，然后编译成招聘页面

这个要是能找到出处，我们参考下。不然就先不加审核

**Comment by tjob-slack** [comment]
说的审核，其实就是核实信息和完善信息，然后再正式发布吧？ 
不一定是功能性流程，可以人工打标记，然后让bot把带标记的发布出去。

**Comment by tjob-slack** [comment]
在哪收集数据、在哪发布页面，这两个前后端的接口定了，后面就可以开始工作了。

**Comment by lovepoem** [comment]
> 可否指导一下，如何操作？
> 比如：要求什么工具，接口，如何发布代码。

https://github.com/wuhan2020/wuhan2020.github.io/pull/170 请参考这个pr，调试发布过程，请看README文档

**Comment by lovepoem** [comment]
> 在哪收集数据、在哪发布页面，这两个前后端的接口定了，后面就可以开始工作了。

直接在评论里面发布吧，简单粗暴点

**Comment by iLtc** [comment]
> 请问“编译成页面” 这步具体怎么实现呢？

就是由机器人把 issue 内容复制到咱们站点的某个目录下，然后咱们站点的引擎编译，跟 blog 模块差不多那样

> @iLtc 说的issue模版，和 @16647615268 你说的gitalk，不知道是不是一样的？

应该不一样，我是指提一个新的 issue，gitalk 会在现有 issue 下增加评论

> 其实我还没有想好审核流程

我觉得审核要稍微做一下，不然别人通过我们平台找工作被骗了，会不会回来找我们？

> 这个要是能找到出处，我们参考下。不然就先不加审核

这是我以前加的一个当地的 ruby group 搞的，后来和大区的 ruby community 合并已经不存在了

**Comment by iLtc** [comment]
> 直接在评论里面发布吧，简单粗暴点

可以理解为直接新建一个页面，然后让用户在评论区发布职位和讨论，对吗？@lovepoem

**Comment by lovepoem** [comment]
> > 直接在评论里面发布吧，简单粗暴点
> 
> 可以理解为直接新建一个页面，然后让用户在评论区发布职位和讨论，对吗？@lovepoem

嗯

**Comment by tjob-slack** [comment]
关于招聘会的需求：
1） 招聘需求的显示：会在项目web主页放个板块？ （ https://community.wuhan2020.org.cn/zh-cn/index.html）
2） 招聘需求的发布：是在项目github填写？ （https://github.com/wuhan2020/wuhan2020）
2.1 ）ISSUE填写我知道，是在issue下面，gitalk在哪里填写？
3）总体需求是需要编写代码，把2）的页面，在1）下面显示，是这样吗？  
3.1）那么写代码和github bot机器人是什么关系?

**Comment by tjob-slack** [comment]
![webwxgetmsgimg (1)](https://user-images.githubusercontent.com/60630538/77931170-66ba1a00-72de-11ea-870c-0d1eeb76f9cb.jpg)
页面设计建议

**Comment by tjob-slack** [comment]
![image](https://user-images.githubusercontent.com/60630538/77931305-9832e580-72de-11ea-82db-51a5c8ce7481.png)
页面设计建议

**Comment by tjob-slack** [comment]
下面这个图是不是gitalk？  引自 #497
![image](https://user-images.githubusercontent.com/60630538/77973994-6e9eac00-7328-11ea-95ee-9f29de30e067.png)

**Comment by iLtc** [comment]
是的

**Comment by tjob-slack** [comment]
请教”招聘汇“目录在哪里创建？
（计划：目录创建后，1）有个基本页面  2）把gitalk先挂上去）

**Comment by tjob-slack** [comment]
实现思路：
1）入口：一个readme的markdown页面。说清楚怎么按模板写招聘需求。
2）招聘方在评论区填写招聘需求
3）(页面打开时)自动从评论抓取招聘需求清单
4） (自动)对需求分类，分类作为菜单目录放入本版块主页
5）点击分类菜单，显示该分类下的具体招聘需求摘要列表
6）点击某招聘需求，打开详情页。 
7）用户可以单个（详情页）或者（列表页）批量申请应聘（待定）（需要另外一个评论仓库保存）
8）调用mermain显示需求和应聘者的分析图表（待定）
