### ISSUE TITLE
[doc] Creation of Brazilian translation

### ISSUE THREAD

**Issue by kevenleone** [wuhan2020/wuhan2020.github.io#52]
Hello,

I've seen on the news many Brazilians living on Wuhan, and I know many others in whole China.
Could I add a translation in Portuguese - Brazil ?

I think this can benefit all the population that speak Portuguese.

**Comment by chenrui333** [comment]
Yeah, of course, can you join the #team-translation channel on Slack?

**Comment by chenrui333** [comment]
Slack invite, https://join.slack.com/t/wuhan2020/shared_invite/enQtOTI2NTU1NzU3MTM2LWQ1YjIzMDllYjYzYTE1OTNhMWU4OTZkOGYzOGJhOWM2MzdlMjgwMmZiOWEzYTQwNmJkZDI4OWRmM2Q2ZDM1MTc

**Comment by kevenleone** [comment]
Of course, I'll join soon, thanks !!!

**Comment by chenrui333** [comment]
Thanks!

**Comment by kevenleone** [comment]
@chenrui333 I'm really busy these days, but when possible I'll help to translate to pt-br, and join in Slack to talk about it.


Thanks for attention

**Comment by chenrui333** [comment]
Feel free to create a PR and start the translation work, we can take in whenever ready.
