### ISSUE TITLE
[doc] Add Italian Translation

### ISSUE THREAD

**Issue by GindaChen** [wuhan2020/wuhan2020.github.io#68]
This is the epic issues for adding Italian Translation. If you're a contributor, it would be great if you can open an issue for each of the sub tasks mentioned here.

@sciulli It would be awesome if you can help coordinate the translation of these documentations to Italian:

- [x] (Resolved in #73 ) [Index](https://community.wuhan2020.org.cn/it-it/index.html) - The index of all 
- [x] [What is Wuhan2020]( https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/docs/en-us/overview/what-is-wuhan2020.md) - This doc serves as the entry point for most dev / people from general public. You can write however you would like to make it more inviting and user-friendly for potential incoming devs
- [x] [FAQ](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/docs/en-us/overview/faq.md)
- [x] [Data Collection Guide](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/docs/en-us/dev/information-guide.md)
- [x] [Guide for contributor](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/docs/en-us/dev/contributing.md)
- [x] [Github Repo Processing](https://github.com/wuhan2020/wuhan2020.github.io/blob/dev/docs/en-us/dev/dev-env-setup.md)

**Comment by GindaChen** [comment]
The index for italian is accessible here:
https://github.com/wuhan2020/wuhan2020.github.io/blob/b1755f5e703824620a154a61ab14af710ec60a37/site_config/home.js#L40-L77

Find the 'it-it' and edit the doc directly

**Comment by lovepoem** [comment]
暂时关闭，如果有问题请随时打开

**Comment by sciulli** [comment]
> 暂时关闭，如果有问题请随时打开

@lovepoem 谢谢，这个issue完全解决的，“guide for contributor”也是完整翻译成意大利语的。
