### ISSUE TITLE
[媒体文章搬到社区网站] 文案1：致 wuhan2020 开源社区全体成员的一封信 

### ISSUE THREAD

**Issue by ch-shumin** [wuhan2020/wuhan2020.github.io#79]
https://mp.weixin.qq.com/s/jFBpUFnSwop4PCGd_5lcWA

标题作者请写媒体和作者名字
请使用 [Typora](https://www.typora.io/)  将`html`页面转化为`markdown`,放到社区频道.图片尽量下载到本站

**Comment by chenrui333** [comment]
Move the issue here as it is more appropriate.
