### ISSUE TITLE
如何加入Slack小组？

### ISSUE THREAD

**Issue by kcxh** [wuhan2020/wuhan2020.github.io#8]

**Comment by GindaChen** [comment]
https://join.slack.com/t/wuhan2020/shared_invite/enQtOTI2NTU1NzU3MTM2LWQ1YjIzMDllYjYzYTE1OTNhMWU4OTZkOGYzOGJhOWM2MzdlMjgwMmZiOWEzYTQwNmJkZDI4OWRmM2Q2ZDM1MTc

**Comment by GindaChen** [comment]
希望你已经加入了Slack～如果链接失效的话可以@我

**Comment by GindaChen** [comment]
@mingao139 Does that solves the problem for you?

**Comment by lovepoem** [comment]
需要在https://wuhan2020.github.io/zh-cn/community/index.html 页面将所有的Slack chanel 列出来

**Comment by chenrui333** [comment]
Fixed in this PR, https://github.com/wuhan2020/wuhan2020.github.io/pull/34
