### ISSUE TITLE
[媒体文章搬到社区网站] 文案10：如何加入到 wuhan2020 开源项目，打赢这场没有硝烟的战争？

### ISSUE THREAD

**Issue by ch-shumin** [wuhan2020/wuhan2020.github.io#86]
中文标题：如何加入到 wuhan2020 开源项目，打赢这场没有硝烟的战争？
中文链接：https://mp.weixin.qq.com/s/YAMMgJH_EU7qzwHxppJXrw
英文标题：How to join wuhan2020 open source project, and survive this war without gunfire
英文链接：https://shimo.im/docs/5b4bb8b4dc064938/

 
标题作者请写媒体和作者名字
请使用 [Typora](https://www.typora.io/)  将`html`页面转化为`markdown`,放到社区频道.图片尽量下载到本站

**Comment by iLtc** [comment]
#158 中文版已提交

**Comment by iLtc** [comment]
#166 英文版已提交

**Comment by GindaChen** [comment]
Fantastic! Thanks for the contribution
