### ISSUE TITLE
[媒体文章搬到社区网站] 文案6-疫情知识 -- 新型冠状病毒防护指南

### ISSUE THREAD

**Issue by ch-shumin** [wuhan2020/wuhan2020.github.io#91]
https://mp.weixin.qq.com/s/hGl-Sm6nXfd4cRfg_P5oqw

标题作者请写媒体和作者名字
请使用 [Typora](https://www.typora.io/)  将`html`页面转化为`markdown`,放到社区频道.图片尽量下载到本站

**Comment by iLtc** [comment]
@alexlinsy The '/self-assign' bot is not working now. I have assigned this issue to you.

**Comment by alexlinsy** [comment]
@iLtc Thanks!

**Comment by lovepoem** [comment]
Closed via  https://github.com/wuhan2020/wuhan2020.github.io/pull/186
