### ISSUE TITLE
[媒体文章搬到社区网站] 文案9- Respected all engineers who are fighting the Novel Coronavirus (2019-nCoV) pandemic behind the screen.

### ISSUE THREAD

**Issue by ch-shumin** [wuhan2020/wuhan2020.github.io#94]
https://shimo.im/docs/0dcc8884a91f473f/ 

标题作者请写媒体和作者名字
请使用 [Typora](https://www.typora.io/)  将`html`页面转化为`markdown`,放到社区频道.图片尽量下载到本站

**Comment by jeremy0519** [comment]
@lovepoem seo写什么？

**Comment by lovepoem** [comment]
> @lovepoem seo写什么？

按照标题，找两个关键词吧

**Comment by jeremy0519** [comment]
那关键词写中文还是英文？



在 2020-02-25 11:29:55，"Xin Wang" <notifications@github.com> 写道：

@lovepoem seo写什么？

按照标题，找两个关键词吧

**Comment by jeremy0519** [comment]
keywords写中文还是英文？
