### ISSUE TITLE
删除！[媒体文章搬到社区网站] 文案11-Wuhan2020 Open Source Project collaboration process released & experts wanted

### ISSUE THREAD

**Issue by ch-shumin** [wuhan2020/wuhan2020.github.io#95]
https://shimo.im/docs/0d51055cc0084fe9/read

标题作者请写媒体和作者名字
请使用 [Typora](https://www.typora.io/)  将`html`页面转化为`markdown`,放到社区频道.图片尽量下载到本站

**Comment by GindaChen** [comment]
所以这个还需要搬运吗？**删除** 是什么意思……

**Comment by lovepoem** [comment]
@ch-shumin 同问删除是啥意思

**Comment by lovepoem** [comment]
和 @ch-shumin 沟通后，她意思是关闭这个issue
