### ISSUE TITLE
[媒体文章搬到社区网站] 文案12-Recruiting! Thanks to those supporting project wuhan2020!

### ISSUE THREAD

**Issue by ch-shumin** [wuhan2020/wuhan2020.github.io#97]
https://shimo.im/docs/6c617d7b5278487f/
 
标题作者请写媒体和作者名字
请使用 [Typora](https://www.typora.io/)  将`html`页面转化为`markdown`,放到社区频道.图片尽量下载到本站

**Comment by Ema1997** [comment]
@ch-shumin 请问是把哪个html转成markdown啊，社区频道大概是哪里？

**Comment by jeremy0519** [comment]
> @ch-shumin 请问是把哪个html转成markdown啊，社区频道大概是哪里？

https://shimo.im/docs/6c617d7b5278487f/
在`/blog/en-us/`里面新建一个`thank-supporting-project.md`，图片放到`/images/blog/media`里面，然后在`/i18n/en-us.js`里面community部分加上入口

**Comment by Ema1997** [comment]
关键词和描述是什么？

**Comment by Ema1997** [comment]
\self-assign

**Comment by jeremy0519** [comment]
关键词从标题里挑两个就行了，描述就写标题

**Comment by Ema1997** [comment]
请问图片应该怎么上传，我upload files的时候，显示没有push权限不能上传

**Comment by jeremy0519** [comment]
放到你的仓库中，然后再一起提pr
