### ISSUE TITLE
添加sitemap生成，方便站内url 提交搜索引擎

### ISSUE THREAD

**Issue by lovepoem** [wuhan2020/wuhan2020.github.io#98]
添加sitemap生成，方便站内url 提交搜索引擎baidu 和google

**Comment by lovepoem** [comment]
![image](https://user-images.githubusercontent.com/827112/73938651-a7bb3100-4922-11ea-9bfa-5fd144ac0e02.png)
https://www.xml-sitemaps.com/

https://github.com/txd-team/docsite-doc-v1/blob/master/docs/zh-cn/SEO.md

**Comment by iLtc** [comment]
这样相当于手动生成了，我写个脚本自动遍历各个语言目录，然后生成 sitemap.xml

**Comment by lovepoem** [comment]
这个得给他的组件提个issue

**Comment by chenrui333** [comment]
where are we with this issue?

**Comment by iLtc** [comment]
I wrote a command-line tool to look through each language folder and then generate the sitemap file. I will merge the tool soon and try to let it run automatically during deploy.

**Comment by lovepoem** [comment]
> I wrote a command-line tool to look through each language folder and then generate the sitemap file. I will merge the tool soon and try to let it run automatically during deploy.

Awesome job

**Comment by lovepoem** [comment]
在线的  sitemap.xml 404 的问题解决了么？ @iLtc @purple-force

**Comment by iLtc** [comment]
什么 404 问题？ https://community.wuhan2020.org.cn/sitemap.xml 正常呀
