### ISSUE TITLE
Failed to register a ServiceWorker for scope. ServiceWorker script evaluation failed

### ISSUE THREAD

**Issue by JinXJinX** [wuhan2020/wuhan2020.github.io#99]
访问或刷新 https://wuhan2020.github.io 页面以及子页面。会收到这条alert提醒

<img width="454" alt="Screen Shot 2020-01-29 at 7 44 32 AM" src="https://user-images.githubusercontent.com/12160296/73358592-facf1d00-426c-11ea-8ffe-39b14618c698.png">

**Comment by lovepoem** [comment]
先临时关闭，有问题请打开
